### ISSUE TITLE
metadata 2.0

### ISSUE THREAD

**Issue by minrk** [takluyver/flit#100]
Flit currently implements [metadata 1.2](https://www.python.org/dev/peps/pep-0345/#license-optional). It should probably consider upgrading to [metadata 2.0](https://www.python.org/dev/peps/pep-0426/). I'm not 100% sure what's involved, or what the downsides are, if any. But since the wheel package has been generating metadata 2.0 for a few years now, roughly all wheels probably use md 2.0, so it seems appropriate / safe.

**Comment by takluyver** [comment]
Metadata 2.0 has 'deferred' status, while both PEP 427 and PEP 491 say that METADATA in a wheel is "the same format as PKG-INFO as found at the root of sdists," not in the 2.0 JSON format. Where possible, I like to stick to the wheel format as specified, rather than doing whatever pip allows.

**Comment by minrk** [comment]
Gotcha. I guess `wheel` produces both the 1.2 email-style and 2.0 json-style files, with metadata-version: 2.0, and the extra fields defined in the PEPs.

This is largely prompted by #99, since md 2.0 has a clear definition of how to include license files in wheels, while md 1.2 leaves it undefined.

**Comment by dholth** [comment]
`wheel`'s json metadata generation has always been experimental. Use the key-value one.

**Comment by flying-sheep** [comment]
The newest accepted version is 2.1 (in [PEP 566](https://www.python.org/dev/peps/pep-0566)). It defines only two new features over 1.2:

- `Description-Content-Type` (added in #169)
- `Provides-Extra` (requested in #144)

I think we should rename this “metadata 2.1” and close it once #144 is closed

**Comment by takluyver** [comment]
We can just close this - we're already using metadata 2.1, and as you point out, #144 exists to discuss 'extras'.
