### ISSUE TITLE
Standalone `flit wheel` package

### ISSUE THREAD

**Issue by FRidh** [takluyver/flit#101]
Could we have a package that does just `flit wheel`, and has no dependencies? That would make bootstrapping a bit easier.

Furthermore, what would it take to add Python 2 support for such a package? 

It has gotten a bit messy now when one wants to install `jupyter` fully from source, since the new dependency `testpath` is a Flit package (although if I recall there was another one as well). While the wheel produced is a universal wheel and so it can be used with Python 2 it messes with our build chain and I'm pretty sure other distributions will experience similar issues. We *can* package wheels, but prefer not to (although the recent choice of `setuptools` to stop vendoring dependencies forces us in that direction).

**Comment by takluyver** [comment]
Most of the dependencies are used when building wheels; I think the only one that's not is `requests_download`, and you can already quietly ignore that for bootstrapping.

I'm experimenting with building sdists from flit; if you want to try this out, grab the sdist branch and use `python3 -m flit.make_sdist`. This would give you .tar.gz files on PyPI which you could use with pip. I'm not committed to this approach yet, though; I'd still recommend developing tools which can start from wheels.

**Comment by FRidh** [comment]
> Most of the dependencies are used when building wheels

Do you plan on keeping external dependencies, or vendoring them? I saw its a mixture now.

> I think the only one that's not is requests_download, and you can already quietly ignore that for bootstrapping.

Indeed, I might have a `bootstrapped-flit` package that doesn't have that dependency.

> I'm experimenting with building sdists from flit; if you want to try this out, grab the sdist branch and use python3 -m flit.make_sdist.

I don't mind using flit, at all, and would be quite happy if I wouldn't have to use `setuptools` :-)

> I'd still recommend developing tools which can start from wheels.

I find it a pity it is going in this direction. While I am glad that one can have packages that don't require setuptools, I think relying on wheels is a step backwards as well since it makes harder to build from source. 

And how about

> Furthermore, what would it take to add Python 2 support for such a package?

I'm not using Python 2 myself, but we still kind of support it...

Thanks for the quick reply.

**Comment by takluyver** [comment]
> Do you plan on keeping external dependencies, or vendoring them? I saw its a mixture now.

I plan on keeping them. I asked for readme to be vendorised because the external packages has some large dependencies of its own (pygments, bleach), which aren't needed for what we're doing with it.

> (sdists...)

I realised that I may not have explained why I was talking about this. If I do add the sdist building machinery, packages built with flit will have an sdist that you can build using pip/setuptools, without needing flit at all. It generates a setup script at build time.

> I think relying on wheels is a step backwards as well since it makes harder to build from source.

For pure-Python packages (which is all flit supports), wheels *are* source, and I like having a strictly structured layout over a setup script. However, I'm pushing for PEP 517, which would allow sdists without a setup.py.

> Furthermore, what would it take to add Python 2 support for such a package?

I'm really trying not to. Flit can build packages for Python 2, and install to Python 2 (`flit install --python path/to/python`), even though the tool itself requires Python 3.

**Comment by leorochael** [comment]
Hi @takluyver,

> I'm experimenting with building sdists from flit; if you want to try this out, grab the sdist branch and use `python3 -m flit.make_sdist`.

Have you considered opening a PR with this branch so we can add comments to it?

IMO, as long as systems like `buildout` depend on sdists and can't use wheels (and PEP 517 isn't implemented), it'd be best if all packages had a `setup.py` carrying sdist on PyPI, even if the `setup.py` is completely auto-generated and not present in the source repository.

**Comment by Carreau** [comment]
> IMO, as long as systems like buildout depend on sdists and can't use wheels (and PEP 517 isn't implemented), it'd be best if all packages had a setup.py carrying sdist on PyPI, even if the setup.py is completely auto-generated and not present in the source repository.

Well [pep 518 implementation](https://github.com/pypa/pip/pull/4144) is moving forward fast as well, so the rest should not be too hard once this is in. So we are not that far from builds without `setup.py` (I hope).

While it is inconvenient to not have `setup.py` everywhere, I don't think requiring all packages to have it is really the "best". You need the carrot and the stick to have people moving forward.

If it is really an issue with  `testpath`, maybe we can release a minor/patch of it that just add a `setup.py` .

**Comment by takluyver** [comment]
> Have you considered opening a PR with this branch so we can add comments to it?

I'm not fully convinced that's the right approach, so I don't particularly want to invite comments on the implementation. It's mostly stuck on the manifest issue - I'm trying to think how to determine cleanly what files go into the sdist. Wheels are easy - you put the package files themselves in, plus some metadata. Sdists are expected to contain things like docs and tests alongside the package:

* The layout of docs, tests and so on is not standard enough to hardcode them into flit itself.
* I don't really want to add a separate file or metadata field to list them. Especially not one with the complexity of MANIFEST.in - every time I change one of those files, I have to look up the syntax.
* Your VCS already knows what files are 'source', but I don't want flit to require a particular VCS, or even to assume it's working on a VCS checkout.

**Comment by leorochael** [comment]
@Carreau:
> While it is inconvenient to not have setup.py everywhere, I don't think requiring all packages to have it is really the "best". You need the carrot and the stick to have people moving forward.

I agree, but until we have an approved standard for a `setup.py`-less sdist, we don't really have a "stick".

@takluyver:

>  - The layout of docs, tests and so on is not standard enough to hardcode them into flit itself.
>  - I don't really want to add a separate file or metadata field to list them. Especially not one with the complexity of MANIFEST.in - every time I change one of those files, I have to look up the syntax.
>  - Your VCS already knows what files are 'source', but I don't want flit to require a particular VCS, or even to assume it's working on a VCS checkout.

I feel your pain, `MANIFEST.in` does kinda suck. And you're right there is no standard of how to specify what gets in the sdist outside of `MANIFEST.in`.

But considering the conflicting goals of "not having a MANIFEST.in-like thing" and "not depending on a VCS", I humbly suggest we start with standard `MANIFEST.in` support and figure out a way to drop it later. The effort of figuring out how to drop `MANIFEST.in` will have to be made anyway, and at least flit gets a working `sdist` implementation in the meantime.

**Comment by FRidh** [comment]
The original questions have been answered so I think we can close this issue. Perhaps the current topic is best discussed in a different issue? 

In any case, regarding the current topic, @takluyver, I think those that would like to have a setup.py don't care so much about building the docs and running the tests with it. Personally, I don't need a setup.py anyway.

**Comment by takluyver** [comment]
> But considering the conflicting goals of "not having a MANIFEST.in-like thing" and "not depending on a VCS", I humbly suggest we start with standard MANIFEST.in support and figure out a way to drop it later. 

Sorry, but I don't want to use MANIFEST.in only to switch to something else later. There's no requirement for it to be there for the install tools, as far as I know, so we can make sdists without ever dealing with MANIFEST.in.

Frederik:
> The original questions have been answered so I think we can close this issue.

Thanks, will do.

> In any case, regarding the current topic, @takluyver, I think those that would like to have a setup.py don't care so much about building the docs and running the tests with it.

Nah, I've uploaded enough sdists to PyPI that I fully expect people to complain if they don't contain docs and tests. And I think it's reasonable to expect an untarred sdist to contain the same files as a fresh VCS checkout.

**Comment by takluyver** [comment]
@leorochael if you want to discuss further, may I suggest #74 as the venue?
