### ISSUE TITLE
Fill in license value as well as classifiers in flit init

### ISSUE THREAD

**Issue by pfmoore** [takluyver/flit#102]
When using ```flit init``` you are prompted for a license. This is used to set the "Classifiers" field in ```flit.ini```. From what I've seen, many packages fill in both the classifiers and the license metadata field (even though "License" is documented as optional).

Would it be worth using the license choice to populate both Classifiers and License in flit.ini?

**Comment by takluyver** [comment]
I've also seen many packages using it that way, but my understanding is that it's meant to be used as an alternative when the desired license is not available as a classifier:
https://www.python.org/dev/peps/pep-0345/#license-optional

**Comment by pfmoore** [comment]
OK. I was surprised that if you omit it, the metadata shows "License: UNKNOWN" even though the classifier is present - but that's just the way the metadata processing works. Scanning my system shows 64 with License set vs 9 without, and of the ones with it set, just under half are variations on what flit init offers (most of the rest are BSD).

So I'd say the advantage of adding it is that people doing naive scans of metadata don't see "License: UNKNOWN" and draw the wrong conclusion, plus a certain level of consistency (I see "License: MIT", "License: MIT License", "License: MIT license", "License: MIT License ", and "License: MIT license "!)

But it's certainly a minor point and if you prefer not to do this, I'm fine with that.

**Comment by warsaw** [comment]
AFAICT, even with the license information in the `pyproject.toml` file, the classifiers are never filled into the generated `setup.py` file.  This results in a PyPI page that lacks the license metadata, and this can break downstreams (e.g. a corporate environment that checks for an acceptable license).

Here's my `pyproject.toml` file from [importlib_resources](http://importlib-resources.readthedocs.io/en/latest/) - and [its PyPI page](https://pypi.org/project/importlib_resources/):
```
[build-system]
requires = [
    "flit",
    "setuptools",
    "wheel",
    ]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "importlib_resources"
author = "Barry Warsaw"
author-email = "barry@python.org"
home-page = "http://importlib-resources.readthedocs.io/"
description-file = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    ]
requires-python = '>=2.7,!=3.0,!=3.1,!=3.2,!=3.3'
requires = [
    "pathlib2; python_version < '3'",
    "typing; python_version < '3.5'",
    ]
```

and here's the generated `setup.py` file:

```
#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['importlib_resources',
 'importlib_resources.tests',
 'importlib_resources.tests.data01',
 'importlib_resources.tests.data01.subdirectory',
 'importlib_resources.tests.data02',
 'importlib_resources.tests.data02.one',
 'importlib_resources.tests.data02.two',
 'importlib_resources.tests.data03',
 'importlib_resources.tests.data03.namespace.portion1',
 'importlib_resources.tests.data03.namespace.portion2',
 'importlib_resources.tests.zipdata01',
 'importlib_resources.tests.zipdata02']

package_data = \
{'': ['*'],
 'importlib_resources': ['docs/*', 'docs/_static/*'],
 'importlib_resources.tests.data03': ['namespace/*']}

extras_require = \
{":python_version < '3'": ['pathlib2'], ":python_version < '3.5'": ['typing']}

setup(name='importlib_resources',
      version='0.5',
      description='Read resources contained within a package.',
      author='Barry Warsaw',
      author_email='barry@python.org',
      url='http://importlib-resources.readthedocs.io/',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=2.7,!=3.0,!=3.1,!=3.2,!=3.3',
     )
```

**Comment by takluyver** [comment]
I've marked this as closed by #402. 'License' is not a required field according to the [core metadata spec](https://packaging.python.org/specifications/core-metadata/), and with that change, the License field will simply be omitted rather than indicating `UNKNOWN`. I hope that's clearer.

It looks like PEP 639 will give us some more structured way to record license metadata in the future.

**Comment by techtonik** [comment]
Instead of `LicenseRef-Public-Domain` I would prefer PEP 639 to include more explicit way of copyright opt-out. Otherwise it looks like a hack to me.

**Comment by takluyver** [comment]
You'll need to take that discussion up elsewhere - I'm not involved in PEP 639.
