### ISSUE TITLE
This is a great package

### ISSUE THREAD

**Issue by choldgraf** [takluyver/flit#108]
Just FYI - super useful. Thanks :-)

feel free to close the issue ;-)

**Comment by takluyver** [comment]
Thanks Chris! Has @Carreau been evangelising it to you?

It's just gaining the ability to make sdists as well, so it should be even more useful in the future.

**Comment by choldgraf** [comment]
haha he did mention it, but only because I explicitly asked him if there was a package designed to make pip-ifying your module more easy...turns out there was such a package :-)

**Comment by dholth** [comment]
Can reproduce.

**Comment by takluyver** [comment]
:-)

Let me know if you work out a fix!

**Comment by dholth** [comment]
You know it. https://bitbucket.org/dholth/enscons might make pip-ifying your packages more hard.

**Comment by takluyver** [comment]
"We choose to do this, not because it is easy, but because it is hard" :-P

Part of my aim was to separate the easy cases from the hard ones. Distutils and setuptools have a lot of flexibility if you can work out how to subclass their commands, but 95% of the time we're using them to package up a few straightforward .py files. I figure that if flit makes it really easy to package straightforward pure-Python libraries, that frees other tools like enscons to focus on things like compilation and code generation.

I'm sure that eventually someone will ask for flit to support some kind of configurable build step, though.

**Comment by dholth** [comment]
I like flit and mine has stalled. Thanks for keeping at it.

**Comment by takluyver** [comment]
While you're both being nice about flit, could I ask for your input on something?

What commands would you look for to:
1. Create a wheel and an sdist together.
2. Create and upload a wheel and an sdist.

I've currently called these `flit build` and `flit upload`, but I'm not sure about `flit build` in particular. 'Build' might be a bit of a jargon term, and it could be confusing if we later want to add the option for a build step before making a wheel (not saying we will, but who knows). Maybe `flit package` would be better? Or maybe you have a better idea?

**Comment by choldgraf** [comment]
I actually thought `flit package` when I first read point 1, then I saw you mentioned it below. I'm +1 on that.

instead of `flit upload` why not `flit push`? Fits within the broader ecosystem of "things that push'

**Comment by takluyver** [comment]
Interesting idea! I might be a bit concerned about people confusing `flit push` and `git push`, though.

**Comment by takluyver** [comment]
I have also wondered about `flit release` instead of `flit upload`, but I'm not convinced about that - uploading is only one step of making a release.

**Comment by choldgraf** [comment]
my 2 cents: if someone is sophisticated enough to be wanting to create their own `pip` distribution, then they should be able to grok the diff between `flit push` and `git push`. I agree it's a little confusing since they're so similar acoustically, but I think folks would figure it out.

Either way I think it should be `flit <verb-that-corresponds-to-what-we're-doing>`. This is why "push" makes the most sense to me. "Release" sounds a bit ambiguous as to what we mean ("are we creating a release, or are we 'releasing' our package to the wild?")

**Comment by takluyver** [comment]
Yeah, I was thinking of the similar sound - if you're leaving the office, and you ask a colleague to "finish that work, commit, and git push", they might think you said "flit push". Or maybe people would think that flit is some sort of wrapper around git. I'm probably overthinking this, though - I agree that it's not hard for people to work out.

**Comment by Carreau** [comment]
In the end, should not all of that be integrated into pip ? It seem like pyproject.toml and pep 517/518 are just a first step. (I like `upload` and `build` but I'm biased so don't count me too heavily) 

[troll]
Just add a Makefile that invoke flit, and call the steps `./configure`,  `make`, `make install`
[/troll]

**Comment by takluyver** [comment]
:trollface: 

Maybe it will all get integrated into pip one day, but I think that's far enough away that I still want to design a nice UI for it in flit.

**Comment by choldgraf** [comment]
I am a fan for consistency in naming / APIs / conventions across packages, even if those names aren't ideal, so I am +1 for `flit push` and 50/50 between `flit package` and `flit build`.

Next thing will be to write a meta package called "flit_steal" that automatically uses pip to download a package, then uses flit to publish it to `pip` under a new name.

**Comment by takluyver** [comment]
Ha!

**Comment by Carreau** [comment]
> then uses flit to publish it to pip under a new name.

And all names that are levenstein distance of 1 from the original package.

**Comment by takluyver** [comment]
#56 reminded me of another possible verb,  which is `publish`.

**Comment by takluyver** [comment]
How does `flit publish` strike people as an alternative to `flit upload` or `flit push`?

**Comment by choldgraf** [comment]
I like `flit publish`!

**Comment by takluyver** [comment]
I quite like it to read, but I've tried typing it a few times, and hitting the `ubl` combo with fingers 2, 1, 3 on my right hand is a bit uncomfortable. `upload` and `push` both score better on this front.

I'm definitely getting obsessive at this point ;-)

**Comment by takluyver** [comment]
Ha, thanks for testing. Let's see how I fare...

flit publish
flit publsih
flit publish
flit publish
flit publish
flit publish
flit publish
flit publish
flit publish
flit publish

Only one went wrong. Maybe it's not as bad as I thought.

**Comment by choldgraf** [comment]
oooh oooh @Carreau you try!

**Comment by Carreau** [comment]
```
flit publish
Ctrl-C
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
Ctrl-V
```

Looks fine to me.

**Comment by choldgraf** [comment]
![](https://media3.giphy.com/media/12ZDIx1Mw1cXVm/giphy.gif?response_id=5925ac482506cffe6259455e)

**Comment by Carreau** [comment]
Without joking:
```
flit publish
flit publish
flit publish
flit publish
flit publish
flit publish
flit publish
flit pulibish
flit publish
flit publish
flit publish
```

It was harder than I thought, but i'm not completely away and did not get breakfast yet.

**Comment by takluyver** [comment]
```
flit publish flit push flit upload
flit publish flit push flit upload
flit publish flit push fluit upload
flit publish flit push flit upload
fliot publish flit push flit uploiad
flit publish flit push flit upload
flit publish flit push flit upload
```

So based on that sample, `flit` is actually the word I have the most trouble typing.

**Comment by choldgraf** [comment]
haha let's just call the package "asdf" and map 'publish' onto "jkl;"

**Comment by takluyver** [comment]
I think I'm coming round to 'publish'. I'm still about even between 'build' and 'package' for the other command. Any other good ideas for that one?

**Comment by choldgraf** [comment]
either one sounds good to me. Which is more akin to what it's actually doing? Packaging or building?

**Comment by takluyver** [comment]
They're both kind of ambiguous. I'd probably refer to that step as 'building', but it can imply some kind of compilation step, which flit isn't doing. I tend to use 'packaging' to refer to the whole process, including preparing the information flit needs to make a package.

**Comment by Carreau** [comment]
can I also had a `flit forge` that submit an updated pr to conda-forge ?

**Comment by takluyver** [comment]
I had a go at pushing [flonda](https://github.com/takluyver/flonda), which can build conda packages from flit metadata without all that mucking around with conda forge. Then I tried it as [wheel2conda](https://github.com/takluyver/wheel2conda), which can do the same, but starting from a wheel instead of flit metadata. I didn't get much traction with either, but it probably wouldn't be hard to give either of them the ability to upload to anaconda.org.

IIRC, the big missing piece of that was a way to map PyPI dependencies to conda dependencies. But you could get round that if you had the package author manually specify a separate list of conda dependencies. Also, I was recently pointed to a system for indexing modules in PyPI packages, which could be a step towards addressing this: https://github.com/LuisAlejandro/pypicontents

**Comment by takluyver** [comment]
With the requirements-mapping machinery and a modicum of sticking-bits-together, I think it should be entirely possible to do something like `pypi2conda my_pkg` to download the latest release of `my_pkg` from PyPI, create conda packages, and upload them to your channel on anaconda.org.

**Comment by takluyver** [comment]
Thanks for your input, by the way. I've changed upload to `flit publish`, and kept `flit build`.

**Comment by choldgraf** [comment]
sweet! thats sounds reasonable to me :-)
