### ISSUE TITLE
Link to RTD docs from PyPI (and vice-versa)

### ISSUE THREAD

**Issue by brettcannon** [takluyver/flit#114]
I just noticed that there's no obvious link from the PyPI description to flit.rtfd.io (or vice-versa).

I'm happy to submit a PR to fix this if you care to tell me how you would like see this solved (text links? Badges?).

**Comment by takluyver** [comment]
Thanks - how does that change look?

**Comment by brettcannon** [comment]
Only thing I would do is drop the `/en/latest` in the link in case someone is very motivated to translate the docs some day. 😄  Otherwise LGTM!

**Comment by takluyver** [comment]
Heh, makes sense, though I'm not holding my breath.

**Comment by brettcannon** [comment]
😄 neither am I.
