### ISSUE TITLE
Use appdirs maybe?

### ISSUE THREAD

**Issue by Shir0kamii** [takluyver/flit#117]
Hi,

I love flit, I use it more and more to package, so I want to contribute back.

When I was browsing your code, I saw a function dedicated to getting the user data dir.
Maybe you don't know, but there is the `appdirs` package that does that pretty well in a portable fashion, so maybe you'd like to use it.

But I don't know if you're more in favor of reducing code to maintain, or staying as dependency free as possible so I open this issue. 

If you'd like to give it a try, tell me and I'll submit a pull request!

**Comment by takluyver** [comment]
Thanks for the offer - and for your kind words about flit. :-)

I guess you mean [get_cache_dir()](https://github.com/takluyver/flit/blob/0.11.3/flit/inifile.py#L47)? I think I'm OK with this as is: it's not much code, and it does something that doesn't change much, so it takes very little maintenance effort. I'm not against dependencies, but they do have a cost, and in this case I think that cost outweighs the value of removing the code.

I sometimes worry that if packaging gets too easy, we'll end up like Javascript, with every one line function in its own package. But I trust that Python programmers will find a sensible medium. :-)
