### ISSUE TITLE
.whl includes .gitignored content

### ISSUE THREAD

**Issue by rochacbruno** [takluyver/flit#132]
I am not sure if this is expected but when I do `flit build` it creates the `tar.gz` and also `-any.whl` distributions.

The `tar.gz` respects my `.gitignore` but the `.whl` includes ignored content. 
(I tried setting in my MANIFEST.in but looks like flit ignores this also)

**Comment by takluyver** [comment]
Yes, that's expected - wheel builds do not involve the VCS at all. It should be smart enough to avoid including `.pyc` files, though.

What files are you seeing included which should not be?

**Comment by takluyver** [comment]
And, as you found, it doesn't use `MANIFEST.in`. One of my main motivations for flit was to avoid the need for MANIFEST.in, because I have to look up the syntax every time I write one.

**Comment by rochacbruno** [comment]
@takluyver That is strange because `wheel` and `sdist` are suposed to have the same contents no?

I have some generated files, media files, database files, passwords files, .env files etc
They are all on my `.gitignore` so releasing `sdist` exclude all those files.

Usually I put exclude patterns in `MANIFEST.in` and I agree syntax is not the best, but works for wheels and sdists.

Why `wheel` does not exclude the `.gitignored` files?

**Comment by takluyver** [comment]
Building a wheel deliberately doesn't use any information from the VCS. It simply zips up the whole package you've pointed it to, with whatever it contains. This is partly because that's simple to understand, and partly because it means that making a wheel doesn't depend on any kind of VCS tools.

Why are those other files getting saved inside the package directory? It's best to reserve that space for the code and any data files you expect to ship along with your code.

**Comment by rochacbruno** [comment]
>  It's best to reserve that space for the code and any data files you expect to ship along with your code.

I know and I try to follow this when I can, but for some legacy projects here we have some assets generated at runtime that cannot be included (neither deleted because they are part of development environment)

In my understanding I think the best would be:

1.  Project have a repository in github with many files
2. The sdist is generated with the same files
3. The wheel is generated with the same files

So repo, sdist, wheel has exact the same file tree and flit already achieve this by using the `.gitignore` which I think is very clever. (not for those who are not using vcs) 

Is there a reason to build `wheel` in a file tree different of `sdist`?

**Comment by rochacbruno** [comment]
I know you don't like to add more `flags` but one way is to keeo it optional.

```
flit [sdist wheel publish build] [--vcs]
```
while `--vcs` can be enabled by default or even having it as option in `flit.ini` `[flit]` section.

**Comment by takluyver** [comment]
It looks like, once PEP 517 support is implemented, `pip install .` will work by trying to build an sdist, and if that succeeds, using it as the source for building a wheel.

So one option for the future is that `flit build` makes an sdist first, and then builds the wheel from that, while `flit wheel` remains as the quick-and-dirty option to build a wheel directly.

**Comment by takluyver** [comment]
In flit 0.12, `flit build` builds an sdist first, then unpacks that and uses it to build the wheel. So the wheel should not include any files that aren't in the sdist.
