### ISSUE TITLE
[Question] Is setup.cfg ignored?

### ISSUE THREAD

**Issue by rochacbruno** [takluyver/flit#134]
Hi

If I have `setup.cfg`

```ini
[bdist_wheel]
universal = 1
```

Is that ignored? where should I put the `universal` information?

**Comment by takluyver** [comment]
`setup.cfg` is completely ignored (though flit will use its successor, pyproject.toml, in the future). The wheels flit builds are only affected by `flit.ini`, files specified by that, and the contents of the package.

Flit builds universal wheels by default. The choice is between that and a Python-3-only wheel, which you get by specifying `requires-python = >=3` in `flit.ini`.
