### ISSUE TITLE
Support for extras_require

### ISSUE THREAD

**Issue by brettcannon** [takluyver/flit#144]
I was trying to port gidgethub to Flit, but  then I realized I had some `extra_requires` entries:

https://github.com/brettcannon/gidgethub/blob/576a64f57fccba85e6060350491e33a8d0185ac6/setup.py#L37-L45

Is there any support for this sort of stuff in Flit that the docs don't cover? If not, any thoughts on adding support?

**Comment by takluyver** [comment]
Not explicitly. You could try specifying them with environment markers, like `sphinx; extra == 'docs'` (borrowing from [here](https://packaging.python.org/specifications/core-metadata/#provides-extra-optional-multiple-use), but I don't know if it's legal without the `Provides-Extra` metadata, which flit doesn't set.

**Comment by takluyver** [comment]
As for adding support: may be neatest to limit it to the new toml config.

**Comment by brettcannon** [comment]
Yeah, I figured if you said, "no support ATM, but okay to add" it would be something like a `[flit.extras]` section where each key was the extra and the value was the dependencies.

**Comment by brettcannon** [comment]
If flit supported this, would e.g. `pip install -e .[dev]` work by any chance? I'm just trying to think if there's any generic way to install developer dependencies for `pyproject.toml`-using projects instead of having to e.g. detect `flit` in the `pyproject.toml` and then run `flit install`.

**Comment by monkeez** [comment]
I'd really like the ability to use extras_require too, I'm stuck using Python 2.7 so I can't use `flit install` with dev-requires on my CI test server. I was hoping I'd be able to do something like use a build stage running Python 3 to use flit to build a wheel, then in my test stage running Python 2.7 I'd use something like: `pip install -e .[test]`.
