### ISSUE TITLE
Dash in dist-name

### ISSUE THREAD

**Issue by asvetlov** [takluyver/flit#149]
I'm working on https://github.com/wikibusiness/aiohttp-remotes library

The library has a dash in the name but top level package is obviously named with underscore.
`flit` supports `dist-name` option: `dist-name="aiohttp-remotes"`

In this case `flit build` produces correct wheel and tarball names but `pip install` is screwed.
It actually installs the distribution (I could do import it etc.) but `pip freeze` don't see `aiohttp-remotes` installed in virtual environment, `pip uninstall aiohttp-remotes` fails -- no such library was installed from `pip` perspective.

As partial solution I've dropped `dist-name` directive from `pyproject.toml`.
What is recommended way for supporting dashes instead of underscores in package names?

**Comment by takluyver** [comment]
It looks like the `.dist-info` folder needs the name to be normalised to use underscores. You're not doing anything wrong, it's just a bug in flit.

I think it also doesn't matter whether you use `-` or `_` on PyPI - they'll both work for installing the package anyway. But we should make sure it works properly.

**Comment by takluyver** [comment]
#150 should clear it up.

**Comment by asvetlov** [comment]
Recently linux package maintainers asked me to use dashes in library names (`aiohttp-sesssion` for example).
IIRC some linux distros use PyPI tarballs for automatic repackaging.
Is it possible to keep `-` in tarball and replace it with `_` for wheel -- as `setuptools` already does?

P.S. 
I'm trying to use `flit` in my new pure python projects and very happy with it.
Much less dances with deployment comparing to `setup.py`.
Very thank you and please keep the project going.
Supporting C Extensions is another pain, maybe I should try enscons

**Comment by takluyver** [comment]
Once #150 is merged and released, you should be able to go back to what you were doing (`dist-name = "aiohttp-remotes"`), and it will hopefully work as you expect.

I'm puzzled why Linux distro maintainers should care, though. We have several Jupyter/IPython packages with underscores in the name (e.g. [jupyter_core](https://pypi.python.org/pypi/jupyter_core)), and I don't recall anyone asking us to do it differently. It makes more sense to me to do it that way, because then the distribution name matches the import name.

**Comment by takluyver** [comment]
PS Thanks, I'm glad you're enjoying using Flit!

**Comment by asvetlov** [comment]
I don't know.
Perhaps it depends on distribution tooling.
Anyway the change was easy for me and didn't break anything -- so why not?

**Comment by takluyver** [comment]
No reason why not, I'm just not sure why - they must have tooling that can handle both. Anyway, it's a valid thing to do, so we'll ensure that it works.

**Comment by asvetlov** [comment]
Any plans for a new bugfix release?

**Comment by takluyver** [comment]
Tada, 0.12.3 :-)

**Comment by asvetlov** [comment]
Thanks!
