### ISSUE TITLE
Are multiple authors supported?

### ISSUE THREAD

**Issue by warsaw** [takluyver/flit#153]
Our project has multiple authors and especially multiple `author_email`.  It doesn't seem like this is supported.  flit turns it into `author_email="alice@example.com\nbob@example.com"` but this is not accepted by PyPI for upload.  Neither is the multiple addresses separated by a comma.  I gather from this that it's not supported, but it may not necessarily be a flit problem.

**Comment by takluyver** [comment]
The [Author-email metadata field](https://packaging.python.org/specifications/core-metadata/#author-email-optional) is only described for a single address. I don't know if tools handle multiple addresses separated by some delimiter there. I'm not even sure if any tools actually use the author-email field: do you know of anything that's affected by it?

**Comment by warsaw** [comment]
Yes, `flit publish` fails with multiple authors because PyPI rejects (with 400 IIRC) it.  PyPI apparently requires an single valid email address in that field.

Cool, I think I'll engage with the PyPA about this.  The only possible thing flit could do is validate that field itself and warn the user (or reject it) before PyPI complains.

**Comment by takluyver** [comment]
Yep, one of my next goals for flit is to do a whole lot more validation before uploading, so that we can correct issues before we're trying to do a release.

**Comment by di** [comment]
IMO this is a bug in Warehouse, as the `Author-email` and `Maintainer-email` fields should be accepted if they're a valid RFC-822 `From:` header ([per the Core Metadata spec](https://packaging.python.org/specifications/core-metadata/#author-email-optional)), which can include multiple addresses.

See https://github.com/pypa/warehouse/issues/2679.

**Comment by di** [comment]
> Yep, one of my next goals for flit is to do a whole lot more validation before uploading, so that we can correct issues before we're trying to do a release.

I think it'd be great if there was a canonical way to validate metadata provided by [pypa/packaging](https://github.com/pypa/packaging) which could be shared by Warehouse, twine, flit, etc. Perhaps this is something we can collaborate on. 🙂

**Comment by takluyver** [comment]
I'm happy to work together if it makes sense. You can see the validation code that I added recently in the [flit.validate](https://github.com/takluyver/flit/blob/master/flit/validate.py) module.

It's deliberately quite hands-on code, rather than defining a schema and comparing the metadata against it. I think this approach can give more helpful error messages, but I imagine that if there's a common standard validation mechanism, it might be appropriate to make it more formal.

**Comment by di** [comment]
FYI, the incorrect behavior by Warehouse has been fixed in https://github.com/pypa/warehouse/pull/2904.

**Comment by takluyver** [comment]
Thanks! I'll add similar email validation to flit (issue #157).
