### ISSUE TITLE
force installation from flit

### ISSUE THREAD

**Issue by mattijn** [takluyver/flit#156]
Great package! Thanks.

I would like to do:
`flit install --force --upgrade`

or 
`flit install --ignore-installed`

like I would do using `pip`. 

Now I've to update versions even for tiny changes locally

**Comment by takluyver** [comment]
`flit install` internally builds a wheel and passes it to pip. You can use [environment variables](https://pip.pypa.io/en/stable/user_guide/#environment-variables) to set any pip options (like `PIP_IGNORE_INSTALLED=1 flit install`).

If you're developing a package and want to test the changes, you can use `flit install --symlink` (or `flit install --pth-file` on Windows). That will link the source of the package to the install location, so you don't need to do reinstall it when you modify it.

**Comment by mattijn** [comment]
Ah, this `flit install --pth-file` is a clever one! great
