### ISSUE TITLE
Installing a Python package from Github fails

### ISSUE THREAD

**Issue by gkabbe** [takluyver/flit#158]
When I try to install a Flit package from Github, for example via

```
flit installfrom github:takluyver/flit
```

Flit only complains with the following message:

```
Neither pyproject.toml nor flit.ini found, and no other config file path specified
```

This also happens if I specify the full URL (https://github.com/takluyver/flit)

**Comment by takluyver** [comment]
Oh, it's checking for that file before it goes into the `installfrom` subcommand. I think you can work around it by running the command from a directory that has a `pyproject.toml` file in. I'll fix it for the next release (and at some point, the `installfrom` command will be redundant once pip supports PEP 518).

**Comment by flying-sheep** [comment]
now we’re stuck between a rock and a hard place: this is still an issue and pip still doesn’t support PEP 518 fully (i.e. still expects setup.py)

**Comment by takluyver** [comment]
Paul Moore [is working on PEP 517 support in pip](https://github.com/pypa/pip/issues/5407#issuecomment-412657550).

But this is a separate issue: it should just skip the checks for the toml/ini files when you use `installfrom`.

**Comment by flying-sheep** [comment]
exactly. right now the situation is that you can’t install a flit-powered package directly from a git repo in one short command. The options are

1. git clone → pushd → flit install → popd → rm -rf
2. wait for this to be fixed and released
3. wait for pip with PEP 517 support to be released

**Comment by flying-sheep** [comment]
true! but if #206 is enough, we could just quickly release 1.1.1 with that, right?
