### ISSUE TITLE
provide a way for plugins to provide version metadata

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [takluyver/flit#167]
Hi, i'm the author of setuptools_scm, i'd like to get something working quite similar for flit so i cant start using it instead of setuptools for my newer projects

**Comment by takluyver** [comment]
Sorry that this reply has taken a few days, and sorry for what it's going to be. ;-)

I don't have any plans to introduce a plugin system at the moment. I'm not saying it will never happen, and I'll keep this kind of use case in mind, but at present I think the simplicity and consistency of having 'one way to do it' outweighs the value of flexibility. That's simplicity in the implementation, but more importantly from a user perspective: the fewer different ways there are to use Flit, the more you know what to expect with any project that does.

This relates to something I've been thinking about recently: in certain domains, people seem to understand a tool better if there's a kind of conceptual moat around it. Tools that are totally interoperable and flexible as a part of a larger ecosystem seem to get lost in the throng. I haven't really figured out when this applies and what the trade offs are - obviously flexibility and interoperation are virtues. But I think part of the reason that Flit has become the most popular of my personal projects is that it's clearly differentiated from all of the layers built around distutils.

**Comment by RonnyPfannschmidt** [comment]
in that case flit will never be a tool i can use since it wont be possible to support release automation in a sustainable/sane manner
