### ISSUE TITLE
Is `pip 10.0` able to install `flit` based package? (answer: not yet)

### ISSUE THREAD

**Issue by vlcinsky** [takluyver/flit#172]
`pip` version 10 was announced (today?) and it declares some limited support for `pyproject.toml`.

My expectation was, that I could have a `flit` based project and install it by:
```
$ pip install .
```

Short experiment shows, this is not yet true. Searching for [doc describing level of PEP518 support](https://github.com/pypa/pip/pull/5065/files) it looks like current support in `pip` reads `pyproject.toml` but it works well only if it works with `setuptools` and `wheel` as up to now.

To me it sounds like `pip 10.0` does not fully support installation of `flit` based packages.

I am aware of the fact, it must be resolved at `pip` project, but as people might have similar expectations from declared PEP518 support, it might be handy to say somewhere (flit's README.rst, here or in docs) that pip 10.0 does not yet support simple installation of `flit` based packages, but such support is anticipated in upcoming versions.

**Comment by takluyver** [comment]
There are two related PEPs - to support this, pip will also need to implement [PEP 517](https://www.python.org/dev/peps/pep-0517/). I made a [pep517 module](https://github.com/pypa/pep517), so it should be relatively simple to integrate it into pip. But nothing's ever as simple as it should be, and pip has quite a bit of complexity there for historical reasons, so it may not be easy.

**Comment by vlcinsky** [comment]
@takluyver Thanks for clear answer

My understanding is:
- **Regarding pip version 10.0, support for installing `flit` based package _from source_ using only `pip` is not yet present.**. Such option is expected in some future `pip` version as both PEP517 and PEP518 will be supported.
- Installation of `flit` built and published packages is not affected (so **existing `pip` will install `flit` _built_ package without problem**)

This issue shall serve those, who would like to clarify this question so I am closing this issue.

**Comment by takluyver** [comment]
Thanks @vlcinsky , your understanding is correct.
