### ISSUE TITLE
Instructions on how to boostrap

### ISSUE THREAD

**Issue by mpacer** [takluyver/flit#177]
#Now that you've closed #163 and removed boostrap_dev.py in 29dbe93af9005487e14a85da4e0e7c408f536231, you have no explicit instructions on how to get started using flit.

In #163 you say that as long as the requirements are installed `python -m flit install --symlink` will work, but if the requirements aren't installed, then it won't (and you don't say this anywhere in the README). 

I'm not sure what you actually want people to do… or I'd make a PR fixing the README. 

Personally, I ended up using `pip install -r requirements-test.txt`, but that seems like you might have another idea for what the purpose of that is (specifically if it's to be able to run the flit tests rather than to set up a dev install of flit). If that is supposed to be the general requirements file, should we rename it to `requirements.txt`?

**Comment by takluyver** [comment]
To simply get started using flit, you just need to `pip install flit`, as described in the README.

I'll add a note about installing from source, which boils down to:

```
pip install docutils requests
python3 -m flit install
```
