### ISSUE TITLE
I've ignored and committed, but FLIT claims that I haven't.

### ISSUE THREAD

**Issue by ericatai** [takluyver/flit#180]
Hi folks.

I'm looking forward to the simplicity of FLIT but I'm seriously stuck trying to publish.

I've ignored and committed my various project files in GIT, but FLIT claims that I haven't.  I don't know what else to try.

Python 3.5.4
Flit 1.0
Pycharm Community Edition

**Comment by ericatai** [comment]
Thanks much for your super-prompt reply!
Your ls-files experiment show all the stuff that I had asked PyCharm to ignore:
various .idea files
various __pycache__ files
I'm not sure where PyCharm writes GIT's ignore information.  When I look in the .git directory none of the contents seem helpful.  And there is no .gitignore file in my ~ or in my c:/Users/peterel

**Comment by ericatai** [comment]
Maybe I wasn't careful enough and checked in these files.  Even though I am old enough to know better.

**Comment by takluyver** [comment]
The `.gitignore` file normally goes inside the repository itself, though it's also possible to configure a global gitignore file. I don't know exactly how Pycharm interacts with it, because I edit the `.gitignore` directly. What are you doing in Pycharm to ignore the files?

**Comment by ericatai** [comment]
There is a "Version Control" tab in the region under the code navigator region.
There is a check-list-like icon that brings up a popup entitled "Configure Ignored Files".
One can ignore files, directories, and patterns.  I explicitely ignored the .ideas directory and the __pycache__ pattern.
PyCharm knows I'm using GIT and communicates with GIT-HUB nicely.

**Comment by ericatai** [comment]
I found a couple of example .ignore files and am creating a global one outside of PyCharm.
Then I'll figure out the deletion.
