### ISSUE TITLE
Uploading package to a private git repository

### ISSUE THREAD

**Issue by ephraimberkovitch** [takluyver/flit#197]
Hi,
I did not find a possibility to upload flit-generated package to a prove git repository.
Does this option exist?
If not, it would be great to have it.
If yes, I would be happy to know how to do it.
Thanks a lot in advance,
Ephraim

**Comment by takluyver** [comment]
There's no specific support, but `flit build` will give you the package files, and then you can put those wherever you want.

**Comment by takluyver** [comment]
If that's a satisfactory answer, I'll close the issue, as there's nothing to work on. It's still findable if people want to refer to it.
