### ISSUE TITLE
Flit doesn't install a newer version of the dependency (sometimes)

### ISSUE THREAD

**Issue by Mariatta** [takluyver/flit#200]
Thanks for releasing flit 1.1!

I tried using it in https://github.com/brettcannon/gidgethub/pull/64

I came across one problem, it might be a problem with the new release, but I'm not quite sure. The Travis build is failing on Python 3.6.3 environment, but passing everywhere else. (3.6.5, 3.7, nightly). 

I have the following extras:
```
[tool.flit.metadata.requires-extra]
...
aiohttp = ["aiohttp"]
treq = ["treq", "twisted[tls]"]
...
```

`aiohttp` has the dependecy attrs 17.3.0, while twisted has the dependency attrs 17.4.0.

It seems like on Python 3.6.3 environment, `flit install --deps develop` installed only attrs 17.3.0, but not 17.4.0.

https://travis-ci.org/brettcannon/gidgethub/jobs/420911932#L471

But no issues with Python 3.6.5. 
https://travis-ci.org/brettcannon/gidgethub/jobs/420911933

**Comment by Mariatta** [comment]
There is an open bug in pip with similar behavior: https://github.com/pypa/pip/issues/988.

**Comment by takluyver** [comment]
When you `flit install` without `--symlink` or `--pth-file`, it builds a wheel and runs pip to install that. Build a wheel with `flit build` and check whether the metadata is correct - if it is, then I think this is pip's issue.

**Comment by Mariatta** [comment]
Thanks. I tried doing `flit build` but it was still the same problem. I guess it is `pip`'s issue then.

**Comment by takluyver** [comment]
I'd check the metadata in the wheel manually - it's possible there's something wrong with the wheel flit creates. I suspect it's pip's issue, though it may also be an issue pip can't easily fix.
