### ISSUE TITLE
Inconsistency in the docs about version constraints on pyproject.toml requires/requires-extra

### ISSUE THREAD

**Issue by gpfreitas** [takluyver/flit#208]
As of 2018-09-19, the docs prescribe adding a version constraint in the `requires` section of `pyproject.toml` according to the `requests` line below:

```
requires = [
    "requests (>=2.6)",
    "configparser; python_version == '2.7'",
]
```

But for `requires-extra`, the docs say "The requirements are specified in the same format as for `requires`", but the example shows (see the pytest line)

```
test = [
    "pytest>=2.7.3",
    "pytest-cov",
]
``` 

`"requests (>=2.6)"` and `pytest>=2.7.3` are not in the same style.

I'd be happy to submit a PR when someone tells me what the fix should be (I'm guessing it should go all as in `requires`?).

**Comment by takluyver** [comment]
The parentheses became optional in PEP 508, and the recommended format is without them. Everything should work either with or without, but I'd be happy to make the examples consistent without parentheses.

I think a space between the name and the version specifier helps with clarity, e.g. `pytest >=2.7.3`.
