### ISSUE TITLE
Distribute non-code files

### ISSUE THREAD

**Issue by bkircher** [takluyver/flit#219]
Is there a way to distribute non-code files (data files, JSON files, image files) along with Python modules with flit?

I want these files to be copied at install time to the package's folder inside `site-packages`. I believe I can achieve this with setuptools with `include_package_data=True` and `MANIFEST.in` files.

**Comment by bkircher** [comment]
"question" label would be a good fit here

**Comment by takluyver** [comment]
Yup, that's one of my favourite features. Anything inside the package folder is automatically included; there's no need to specify them anywhere. This is more than just a convenience; I've found it's easy to forget to add them to lists like MANIFEST.in, and then ship a broken package.

E.g. Flit includes [license templates](https://github.com/takluyver/flit/tree/master/flit/license_templates) as data files within its own package.

**Comment by bkircher** [comment]
Yes, I see. Thanks for the quick response!
