### ISSUE TITLE
Adopt some formatting style (Black?)

### ISSUE THREAD

**Issue by TiemenSch** [takluyver/flit#223]
During my recent stab at Flit's code to support different root directories I found that my linters (Flake8, pycodestyle) went absolutely haywire on Flit's source code. Aside from dissatisfied linters, I found the code style to be rather inconsistent at times, which makes it more difficult to read.

What is your stance on the formatting of Flit's code? I started using [Black](https://github.com/ambv/black) recently, which helps getting uniformity and keeps almost all linters at bay.

The challenge with such a change is that it affects almost all files, which will create conflicts for any remaining PRs.

**Comment by takluyver** [comment]
Strict style linters annoy me, sorry. I know they're in fashion at the moment, and I understand the advantages, but that's not how I like to work. If you're modifying code anyway, feel free to use whatever style you like for the code you're working on, but please don't send 'style cleanups' beyond the code you're working on.
