### ISSUE TITLE
provides_extra .none ...?

### ISSUE THREAD

**Issue by wimglenn** [takluyver/flit#228]
The metadata generated by flit build advertises my distribution as providing an extra called `.none`:

    provides_extras: ['.none', 'doc', 'test']

Was that intended to be publicly available, or is it a bug?  Reading the source, it looks as though this was just supposed to be an an internal token, not actually making it into the final package. I would rather flit not create the `.none` extra in project metadata.

**Comment by takluyver** [comment]
You're right, that's meant to be an internal token, it shouldn't be visible in the resulting packages.

**Comment by wimglenn** [comment]
Here is a minimal setup to recreate the issue.  `flit==1.2.1`

In `pyproject.toml`:
```
[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "example"
author = "wim"
author-email = "wim@example.org"
home-page = "https://www.example.org"
requires = ["wimpy"]
```

In `example.py`:
```
"""my proj"""
__version__ = "0.1"
```

If commenting out the line `requires = ["wimpy"]` in markup, then the `.none` extra is not created.
