### ISSUE TITLE
Support for Pipfile

### ISSUE THREAD

**Issue by serain** [takluyver/flit#237]
Coming from Node.js it feels a very weird for me to have to define my dependencies in both my `Pipfile` and in the `requires` list in `pyproject.toml`. It also appears the there's no integrity checks on  third-party packages?

Should `flit` not support pulling dependencies from the `Pipfile.lock` or `requirements.txt`, and validate hashes if using `Pipfile`?

**Comment by takluyver** [comment]
`pyproject.toml` is for libraries, `Pipfile` or `requirements.txt` is for applications. You shouldn't need both. See [this blog post](https://caremad.io/posts/2013/07/setup-vs-requirement/) for more info - `pyproject.toml` takes over the role of `setup.py` in that description.

I know all these different files and systems are a bit messy; that's a larger problem with the Python packaging ecosystem, and not something I'm trying to solve right now.
