### ISSUE TITLE
flit does not install in current virtualenv if it’s installed outside of the venv

### ISSUE THREAD

**Issue by merwok** [takluyver/flit#241]
I have flit installed globally (in ~/.usr).

When I run `flit install -s` in a virtualenv (activated) to get a develop install, I see the symlink and dist-info files created under ~/.usr.

Expected behaviour: install in the virtualenv
Alternate good output: error message to tell me to install flit in the venv

**Comment by takluyver** [comment]
It defaults to installing in the environment if the library directory is writeable or `site.ENABLE_USER_SITE` is False. Normally both conditions are met in a virtualenv. Here's the code that checks those conditions:

https://github.com/takluyver/flit/blob/fbd7a0d20daffad158d3a80bd8fae183f20114f7/flit/install.py#L139-L162

Can you tell what part of that check is going wrong?

You can also force it to install to the environment with `--env`. If the library directory isn't writeable, this will fail, though.

**Comment by merwok** [comment]
How do I get flit to print the debug logs?

I set a breakpoint and observed:

>      def _auto_user(self, python):
>          if python == sys.executable:
True (it’s a user-global Python installed in ~/.usr and named by VIRTUALENVWRAPPER_PYTHON)

>              user_site = site.ENABLE_USER_SITE
True (but the user site-packages does not exist, I don’t use user installs, only virtualenvs and pipsi)

>              lib_dir = sysconfig.get_path('purelib')
~/.usr/lib/python3.6/site-packages

>          return not test_writable_dir(lib_dir)
False

> You can also force it to install to the environment with `--env`.
> If the library directory isn't writeable, this will fail, though.
With `--env` the install still happens in ~/.usr/lib instead of the virtualenv.

**Comment by takluyver** [comment]
If it thinks `lib_dir` is `~/.usr/lib/python3.6/site-packages`, then from Flit's perspective, it doesn't look like you're in a virtualenv. Normally `sys.executable` would point to a path inside the environment as well.

**Comment by merwok** [comment]
Certainly this is caused by the fact that flit is installed globally (in ~/.usr), not in the virtualenv.

**Comment by takluyver** [comment]
Ah, gotcha. In that case, you'll need to pass `--python path/to/env/bin/python` for it to install into that virtualenv. Otherwise it installs into the env it's in. This is the same for pip, but setting up a virtualenv normally installs pip in it, so you're less likely to run into it.

**Comment by merwok** [comment]
The behaviour makes sense.  I will make sure to add `pip install flit` to my README to avoid the problem!
