### ISSUE TITLE
Undefined name: 'register' in upload.py

### ISSUE THREAD

**Issue by cclauss** [takluyver/flit#242]
__register__ [was removed in v1.0](https://github.com/takluyver/flit/blob/master/doc/history.rst#version-10) but the function is still called but the [definition of that function can not be found](https://github.com/takluyver/flit/search?q=register&unscoped_q=register).

[flake8](http://flake8.pycqa.org) testing of https://github.com/takluyver/flit on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./flit/upload.py:261:13: F821 undefined name 'register'
            register(metadata, repo)
            ^
1     F821 undefined name 'register'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by takluyver** [comment]
It's no longer necessary to register a package before uploading it, so the try/except to register a package can go away. We should also clean up the docstrings in that file that refer to registering a distribution.

Marked as good first issue, because this is a simple change.

**Comment by takluyver** [comment]
It's no longer necessary to register a package before uploading it, so the try/except to register a package can go away. We should also clean up the docstrings in that file that refer to registering a distribution.

Marked as good first issue, because this is a simple change.
