### ISSUE TITLE
[Question] Python 2.7 installation in CI

### ISSUE THREAD

**Issue by madsmtm** [takluyver/flit#244]
Let's say I'm developing a package that's Python 2.7 compatible.

I'd like to run tests on this package in CI, against multiple Python versions. Most CIs allow easily specifying the Python version, but by doing so, I can't `flit install` required packages (since `flit` won't run on Python 2.7).

So I'd like to ask for suggestions on how to do this properly. Should I somehow build the package beforehand? Should I duplicate my test-requirements into a separate file, and then install them using `pip install -r` (I don't like duplicating things, but this could be solved by #128)? Or is there a Better Way™?

**Comment by madsmtm** [comment]
As far as I know, I can't use [`flit install --python X`](https://flit.readthedocs.io/en/latest/cmdline.html#cmdoption-flit-install-python), since the CI will only have the single specified Python installed.

**Comment by takluyver** [comment]
I don't have a great way to do this. On some relatively small projects where I wanted to keep Python 2 support, I've duplicated the requirements to install in the test environment as you suggest. Someone else came up with a workaround to install Python 3 on the test environment and used that to run flit - see [flit6](https://github.com/wimglenn/flit6).

I suspect that as PEP 517 gains more widespread support, it's going to be inconvenient to use Flit packaging for packages that still support Python 2. Not impossible, but one will probably need an increasing number of workarounds to the default way of doing things.

**Comment by madsmtm** [comment]
Thanks a lot for the input! I don't suspect anybody will want to support Python 2 forever, but while it still hasn't reached it's [End of Life](https://www.python.org/dev/peps/pep-0373/#maintenance-releases), some of us might want to support it for a little while longer.

I'll close this, as I probably got the best answer I could have hoped for :wink:
