### ISSUE TITLE
Install multiple packages

### ISSUE THREAD

**Issue by saulshanabrook** [takluyver/flit#252]
I have a monorepo with a bunch of different Python packages inside one Github repo. To get started developing on them, you have to install them all one by one, like this:

```bash
flit -f udispatch.toml install --symlink
flit -f uarray.toml install --symlink
flit -f umoa.toml install --symlink
...
```

You also have to make sure you install them in the right order.

It would be great if we could include multiple files to install at once, like this:

```bash
flit -f udispatch.toml uarray.toml umoa.toml install --symlink
```

And it could resolve all the dependencies at once.

**Comment by takluyver** [comment]
I understand the use case, and I don't particularly have a better answer for you, but I plan to keep it with one command operating on one package. I like the simplicity and consistency of this. I don't want to think about resolving overlapping dependencies - Flit is primarily a tool to make packages, and the functionality to install them is more of a convenient extra.

pip should now be able to install packages using flit, assuming you describe each one with its own `pyproject.toml` in a subfolder. It obviously supports specifying multiple packages at once. But it doesn't support doing editable/symlink installs with flit - there are occasional discussions about standardising a hook for that, but no-one has really pushed for it yet. If that were to happen and I was happy enough with the way it worked, maybe `flit install` could ultimately disappear altogether.

**Comment by saulshanabrook** [comment]
Sounds good!

Thank you for your work on this package, it makes my life a lot more pleasant developing Python packages.

**Comment by takluyver** [comment]
Thanks Saul :-)
