### ISSUE TITLE
PEP 561 - Package type information

### ISSUE THREAD

**Issue by meadsteve** [takluyver/flit#265]
Is there anyway to get flit to package type information as described in https://www.python.org/dev/peps/pep-0561/ . I can't tell if I'm missing something or if it's not supported.

**Comment by takluyver** [comment]
At a glance, it looks like it's all based on files delivered as part of the package. If so, just create those files in the right place in your package - flit automatically includes files found within the package directory.

**Comment by meadsteve** [comment]
@takluyver thanks. I think the distools/setup.py version needed to have this file referenced so I was worried it'd be the same here https://github.com/meadsteve/talepy/blob/master/setup.py#L13

**Comment by takluyver** [comment]
Nope, one of the goals of flit was to do away with the need for specifying `package_data` - because it's easy to forget.
