### ISSUE TITLE
Clarify how flit is involved in package install for users

### ISSUE THREAD

**Issue by cdeil** [takluyver/flit#266]
Thank you for making `flit`!
I'm trying it now for the first time for a small Python project I'm starting.

While reading the docs, one major question that wasn't clear to me was:
"Do users need to install flit to install a package made with flit?"

Looking at the `sdist` generated by flit, I see that the answer is "no" - flit generates a `setup.py`, and that doesn't list `flit` as a dependency.

So that's great!

It would just be nice for people like me that know about `setup.py` and `sdist` and previously used that to distribute their packages to get this info what flit does from the docs.

I guess a small addition (1-2 sentences) on the README and frontpage would be an option, or a  new small "What flit does" page, which describes a bit what flit puts in the `sdist` and wheels. This could include a worked example where a listing of the files in the sdist and wheels is made.

---

On the other hand, there's `[build-system]` and https://flit.readthedocs.io/en/latest/pyproject_toml.html#build-system-section says that the `pyproject.toml` tells tools like pip to build the package with `flit`.

Now I'm confused.

This doesn't match with what I see in `setup.py` in the `sdist` (no mention of flit there)

I don't understand why flit isn't simply a tool to take `pyproject.toml` as input and to generate an sdist and wheel, but then in no way involved when installing the package, i.e. why this is needed or useful at all:
```
[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"
```

It makes me think a separate "What flit does" page with a bit more info on what kind of wheel and sdist it produces and when flit is or isn't involved when installing those would be better, if you want to keep the front page simple and for beginners.

Thought?

**Comment by takluyver** [comment]
In general, installing a package will use a wheel, which is unpacked by the installer (e.g. pip) onto the filesystem without running anything from inside the package. Flit doesn't (at least for now) support packages with compiled parts, so the wheels are usable on any platform. The only reason it wouldn't use a wheel is if you explicitly forbid that option.

If you install from an sdist, modern install tools will use flit to build the package, using the interfaces defined in PEP 518 and  517. But this should be transparent to the user - the frontend should install flit into a temporary environment for that purpose.

The generated `setup.py` in sdists is a compatibility shim for tools that don't yet use PEP 517 & 518, and it will ultimately go away.

**Comment by takluyver** [comment]
I'll try to find a way to clarify this in the docs.

**Comment by cdeil** [comment]
@takluyver - OK, so I now understand better what's going on.

> If you install from an sdist, modern install tools will use flit to build the package, using the interfaces defined in PEP 518 and 517. But this should be transparent to the user - the frontend should install flit into a temporary environment for that purpose.

Why this complexity? Wouldn't it already now be possible to **only** create a wheel, and to not need a build tool for install?

Is it because you want to support packages with compiled parts with flit in the future? Or is there another reason the super-simple solution of just having `flit` as a tool (or a new tool) that just reformat things a bit and puts things in a wheel and uploads that not possible?

> The generated setup.py in sdists is a compatibility shim for tools that don't yet use PEP 517 & 518, and it will ultimately go away.

What will go away? The `sdist` altogether, or only the `setup.py` but the `sdist` will remain?

> I'll try to find a way to clarify this in the docs.

Thank you!!!

**Comment by takluyver** [comment]
> Why this complexity? Wouldn't it already now be possible to only create a wheel, and to not need a build tool for install?

When I started flit, it only produced wheels, and I tried to convince people that sdists were unnecessary. This argument did not prevail, and ultimately I've decided there are decent reasons to do sdists:

- They serve as a stable archive of project releases, including things like docs and tests which may be left out of a wheel. Once an sdist is published, it will always be byte-for-byte the same, which isn't (apparently) true of running `git archive` on a tag to produce a tarball (even if you don't move the tag).
- In various situations, people want to install all packages from source. It's easier to build sdists for simple packages than to try to distinguish when a wheel can be considered 'source'.
- Flit may in the future allow some kind of build steps, which would make sdists more relevant. I still haven't decided one way or the other on this. See #119 for more thoughts.

> What will go away? The sdist altogether, or only the setup.py but the sdist will remain?

Just the generated `setup.py`. Sdists will continue with `pyproject.toml` as the new standard entry point for tools to process them (as defined in PEPs 518 & 517).

**Comment by cdeil** [comment]
Thanks for the infos!

I guess it's clear, but this was the unclear part of the docs:

> 4. Run this command to upload your code to PyPI: flit publish

Currently in the docs there's zero information what will happen. As a first-time user of flit and someone that doesn't want to make mistakes when publishing to PyPI, that's super scary.

I would feel much more comfortable with a workflow where I know what will happen, and where I can look at the files that will be uploaded to PyPI, to see their content, and also to run some tests to see if the package works before uploading.

It's great to have a do-all `flit publish`, I'm not suggesting any changes in the tool.
Just improve the docs to explain what's going on.
("Controlling package uploads" at https://flit.readthedocs.io/en/latest/upload.html sounded promising - but it doesn't mention `sdist` or `wheel`, i.e. it's not about controlling what flit will upload)

**Comment by takluyver** [comment]
Does the language in #267 look clear to you?

**Comment by cdeil** [comment]
@takluyver - I would suggest to add another docs package explaining a bit what the ``wheel`` and the ``sdist`` is. Here's a draft that roughly contains the infos you gave in this issue:
https://github.com/takluyver/flit/pull/270

Thoughts?
