### ISSUE TITLE
Why flit?

### ISSUE THREAD

**Issue by guettli** [takluyver/flit#273]
I look at this page: https://flit.readthedocs.io/en/latest/index.html

I have never used flit before and I don't know why I should do it.

Please create  a new section before "Install". Maybe with the title "why" or "Introduction".

Please tell us why you think flit should get used.

**Comment by madsmtm** [comment]
There's a bit of motivation in the [reproducible builds](https://flit.readthedocs.io/en/latest/reproducible.html) section, but agreed, the documentation could use a dedicated "why" section

**Comment by takluyver** [comment]
Thank you for the suggestion, but for now I'm happy with the current state of the landing page.

**Comment by guettli** [comment]
Now I (and other people) understand soon what this package provides. Thank you!

**Comment by brainwane** [comment]
@takluyver I was trying to understand/remember/tell others, just now what `flit`'s design philosophy is and what it tries to provide users. It wasn't obvious to me from the landing page of the docs. I dug around and found #283:

> one alternative to `setuptools` for certain use cases (the simple ones).

and https://github.com/takluyver/flit/issues/20#issuecomment-93020675 :

> I don't want to make `flit init` too complex - it's supposed to be a quick way to get a simple, working config file (with license choice integrated to encourage people to give their code a license). Let's focus on building and uploading packages for now. At some point, perhaps a nicer interactive package metadata editor would be good as a separate tool.

and this issue and the associated pull requests, which helped me a lot.

Is there some way we could include some information about those points somewhere a bit more prominently in the documentation? Or in [the Python Packaging User Guide list entry on flit](https://packaging.python.org/key_projects/#flit) ([source](https://github.com/pypa/packaging.python.org/blob/master/source/key_projects.rst#flit))?

**Comment by takluyver** [comment]
OK, taking another look.

**Comment by takluyver** [comment]
I've drafted some wording in #314.

**Comment by brainwane** [comment]
Thank you @takluyver !
