### ISSUE TITLE
Any support for real scripts (i.e. not just console_scripts entry points)?

### ISSUE THREAD

**Issue by wimglenn** [takluyver/flit#275]
I'm looking at scripts section in docs in https://flit.readthedocs.io/en/latest/pyproject_toml.html#scripts-section but it seems to be more about console_scripts entry points, rather than packaging actual scripts.

Does flit have any support for including scripts (e.g. shell scripts) in your distribution, like setuptools/distutils has with the `scripts` kwarg?  If not currently, is it something that might be supported at a later date?

```
setup(
    name='myproj',
    scripts=['bash_scripts/do-the-thing.sh'],
)
```

Sometimes a script is better if you need to mess with the environment _before_ invoking the python interpreter.

**Comment by takluyver** [comment]
It does not. I don't have any plans at present to add that. I wouldn't say never, but in general, Flit does not aim to cover every possible use case.

You could always mess with the environment in Python and then reinvoke the Python interpreter in a subprocess. You can even use `sys.subprocess` to ensure you get the same Python interpreter that the package was installed with.
