### ISSUE TITLE
No way to download a package from a private repository

### ISSUE THREAD

**Issue by SimLeek** [takluyver/flit#279]
Looking at the docs for the pyproject.toml, I don't see any way to download packages from private repositories, urls, or git links. This used to be necessary for large packages like PyTorch, and is still necessary for some new packages.

Note that this isn't about uploading, which is here: https://github.com/takluyver/flit/issues/197

Poetry currently has this functionality as part of its source block: https://poetry.eustace.io/docs/pyproject/#dependencies-and-dev-dependencies

It'd be nice to have that feature in a smaller tool though.

Is there going to be support for this?

**Comment by takluyver** [comment]
Probably not. Two ways of looking at it:

- `flit install` is being replaced by `pip install .` following PEP 517, so pip is responsible for finding  and downloading dependencies.
- The configuration you write for Flit specifies [abstract dependencies](https://caremad.io/posts/2013/07/setup-vs-requirement/), i.e. saying what is needed, not how to get those packages.
