### ISSUE TITLE
when bootstraping flit, `flit` cli is not found. 

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#28]

**Comment by takluyver** [comment]
It does for me. What is `site.USER_BASE` in the relevant Python? Is `site.USER_BASE + '/bin'` on $PATH?

**Comment by takluyver** [comment]
Oh, and do you have an active virtualenv when you do it? Is `site.ENABLE_USER_SITE` True?

**Comment by Carreau** [comment]
yep, `site.USER_BASE + '/bin'` not in PATH !

**Comment by takluyver** [comment]
OK. In that case, I think `pip install --user` would also fail.
