### ISSUE TITLE
Allow flit to auto-bump the version number

### ISSUE THREAD

**Issue by SimiCode** [takluyver/flit#280]
Can we add a function that auto increases the version number according to a simple specification?

**How?**
Thinking of Having an **_optional_** section like this in the .toml file:
[bumpversion]
base_version = 1.0.0
bump_size = 0.0.1

This would increase my version number by +0.0.1 every time I publish. So the next release would be version 1.0.1, 1.0.2, 1.0.3 .... and When I want to move to to version 2, I would increase the base version to 2.0.0. 
**Assumption:** Flit will always read the package wheel files to know my current version.

I know version names may involve characters but this can be a great start.

@Mariatta  @flying-sheep

**Comment by takluyver** [comment]
I'd rather Flit didn't change anything like this. How to actually make releases is a complex topic in its own right - e.g. do you bump the version number just before or just after a release? How do you handle different release levels, e.g. major vs. minor.

There are a range of different tools for this kind of task, from single-purpose things like [bumpversion](https://github.com/peritus/bumpversion) to richer things like [rever](https://regro.github.io/rever-docs/). I've even made a prototype myself, called modeltee, but I don't have much time to work on it. So I consider this set of challenges out of scope for Flit.

**Comment by flying-sheep** [comment]
Versioneer and get_version do things right: If you’re exactly at a git tag, that tag provides your version number, else you have a dirty version like `1.4.2+33.af56c1` saying that we’re “33 commits after 1.4.2”.
