### ISSUE TITLE
flit install --symlink doest not honor --python for scripts it installs

### ISSUE THREAD

**Issue by sbidoul** [takluyver/flit#285]
Hi,

I have been experimenting with flit recently and I very much like it's approach for development installs (`--symlink`).

I noticed what could be a small issues with such installations.

I have flit installed globally (with pipx).

When I try to install my project with `pip install --symlink --python $(which python)` in a virtualenv, I notice the installed script uses flit's python as shebang instead of the python of the virtualenv.

I believe the problem arises in this `install_script`, called via `install_directly`:
https://github.com/takluyver/flit/blob/f5996dcee05656ca7a1e6ed2e5c82a6e911f4f10/flit/install.py#L171

**Comment by sbidoul** [comment]
At first sight, using `self.python` instead of `sys.executable` works fine.

**Comment by takluyver** [comment]
I think you've understood the cause and likely solution, at least from a
quick look. Want to make a PR? Bonus points if you can figure out a
straightforward test for it.

**Comment by sbidoul** [comment]
I can certainly do a PR. Adding a test requires some study of how the test suite currently work.

**Comment by takluyver** [comment]
Thanks! If you've worked with other test suites for Python projects, Flit's tests will probably make plenty of sense. Here's one you could add to:

https://github.com/takluyver/flit/blob/f5996dcee05656ca7a1e6ed2e5c82a6e911f4f10/tests/test_install.py#L78-L109

**Comment by sbidoul** [comment]
Thanks for the pointer. The tests are quite easy to read indeed. Here you go: #286
