### ISSUE TITLE
Flit support for binary extension modules?

### ISSUE THREAD

**Issue by etijskens** [takluyver/flit#290]
Just wondering. Many of my scientific Python projects involve both python modules and binary extension modules based on C++ and Fortran source code. Does flit have support for packaging binary extension models?

**Comment by takluyver** [comment]
It doesn't. I decided to focus on the easy cases, where the files to be installed are the same as the source files, and leave cases with build steps to other tools.

There's a long-standing issue (#119) to consider allowing build steps. But I haven't gone for it yet.
