### ISSUE TITLE
Is it possible to distribute non-python scripts (destination: bin) via flit/pyproject.toml?

### ISSUE THREAD

**Issue by AndydeCleyre** [takluyver/flit#292]
Looking for an answer to the title question, and if it's yes, then this is a documentation request.

Thanks for flit!

**Comment by wimglenn** [comment]
See https://github.com/takluyver/flit/issues/275

**Comment by takluyver** [comment]
Thanks @wimglenn. To summarise the linked issue: no, it doesn't.
