### ISSUE TITLE
Config to let flit install default to active virtual environment

### ISSUE THREAD

**Issue by uranusjr** [takluyver/flit#294]
Use case: I install only one copy of `flit` (user-wide), and use it for all projects I work on. But even if I activate the environment, `flit install` would prefer the Python it’s installed under over the environment the shell is currently in. My current “workaround” is to use `flit install --python=python`, but that seems quite redundant (and I sometimes forget it with frustrating results).

Proposed solution: Let Flit detect the `VIRTUAL_ENV` environment variable in `find_python_executable`, and use it to choose the executable if avaiable. This is backwards-incompatible, and would need to be behind a config (environ?). So maybe something like…

```py
def _find_default_python_executable():
    if not os.environ.get('FLIT_INSTALL_USE_VIRTUALENV'):
        return sys.executable
    prefix = os.environ.get("VIRTUAL_ENV')
    if not prefix:
        return sys.executable
    if sys.platform == 'win32':
        binpath = os.path.join(prefix, 'Scripts', 'python.exe')
    else:
        binpath = os.path.join(prefix, 'bin', 'python')
    if os.path.isfile(binpath):
        return binpath
    return sys.executable

def find_python_executable(python):
    if not python:
        return _find_default_python_executable()
    ...  # unchanged
```

**Comment by takluyver** [comment]
I understand what you're getting at, and if virtualenv was the only such solution, I might go for detecting it by default. But there's also conda, pyenv, etc. I don't know of any general way to detect all of them.

Maybe a more general solution is to allow an environment variable equivalent to the `--python` option, so you could specify e.g. `FLIT_INSTALL_PYTHON=python` to always find the `python` executable on PATH. Of course, you could still override it with `--python`.

**Comment by uranusjr** [comment]
> Maybe a more general solution is to allow an environment variable equivalent to the `--python` option, so you could specify e.g. `FLIT_INSTALL_PYTHON=python` to always find the `python` executable on PATH. Of course, you could still override it with `--python`.

Sounds like a good solution to me as well. Or maybe a `FLIT_NO_INSTALL_DEFAULT` to require an explicit `--python` would be nice as well, in a similar spirit to pip’s `PIP_REQUIRE_VIRTUALENV`. I don’t really mind typing a few more characters, as long as the tool can stop me when I make mistakes.

**Comment by takluyver** [comment]
Interesting idea. I'd rather go for the `FLIT_INSTALL_PYTHON` option for now - you can kind of hack the no-install-default behaviour using that by setting it to something that won't be found (`FLIT_INSTALL_PYTHON=this-is-not-a-snake`), at the cost of less clear error messages.

**Comment by takluyver** [comment]
(Do you want to make PR?)

**Comment by uranusjr** [comment]
I’ll try to find some time during the weekend for this.
