### ISSUE TITLE
rst description validation may require pygments

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#297]
If a reStructuredText (rst) long description contains code blocks, docutils will try to load pygments to highlight them, and give a warning if it's not there. These warnings are the same mechanism flit uses to detect invalid rst, so the validation fails, and flit refuses to build the project.

Possible solutions:

1. Find some way to suppress that specific warning
2. Recognise and ignore that warning - matching human-readable messages is ugly, but docutils changes very slowly, so it might be good enough.
3. Require pygments. I'm reluctant to do this as it's a relatively big package which flit doesn't really need, and only a subset of projects are affected.

**Comment by flying-sheep** [comment]
Totally does. My builds are failing because `flit install --extras=all` doesn’t install the test dependencies before doing that check: https://travis-ci.org/theislab/anndata2ri/jobs/620084576

**Comment by takluyver** [comment]
Option 1 turned out to be easy - see #357.
