### ISSUE TITLE
reason for `flit <packagename>` ?

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#3]
Cannot this be inferred from the `.ini` file ?

**Comment by takluyver** [comment]
Would you prefer to specify the .ini file name, or do you think it should assume that you're in a directory containing a single package and its .ini file?

I tend to think explicit is better than implicit, but I haven't put a lot of thought into how the command line interface should work.

**Comment by Carreau** [comment]
> Would you prefer to specify the .ini file name, or do you think it should assume that you're in a directory containing a single package and its .ini file?

That how I feel. 

I really like trying rust and cargo. Actually for Cargo, the ini file does not depends on the name of the package, it is `Cargo.toml` (toml, is derived from ini AFAIR)

I technically wouldn't even want to specify wether or not I do wheels/sdist etc, I would have purely `flit build`, `flit upload` as what you build could be set in `flit-pkg.ini`.

**Comment by takluyver** [comment]
For now, the only thing it builds is wheels, so `build` == `wheel` ;-)

I think I like the idea of having `flit upload` to build and upload it. `flit name wheel --upload` is a bit longwinded. Although I kind of like that it conveys that uploading a release is a more significant action than building.

Part of me wants to keep the name in the command line so you can create multiple small packages in the same folder. But that's not something I usually do, and I am trying to optimise for the 90% case.

The `<packagename>-pkg.ini` file is also part of my thinking about making it easy to support PEP 420 namespace packages at some point in the future, but I haven't carefully thought through how that would work.

**Comment by Carreau** [comment]
All make sens. 
But I guess you could have a per directory `flit.pkg` that basically does not require user to think at which package (s)he is building/uploading. 

To give you some courage, here is a logo. Need to find another font if you want to use it though.
![capture d ecran 2015-03-27 a 17 47 21](https://cloud.githubusercontent.com/assets/335567/6879131/e4258d5e-d4a9-11e4-9b95-30af564baa76.png)

**Comment by takluyver** [comment]
Ha, where did you come by that?

**Comment by Carreau** [comment]
Come by ? I did it ! (the font is just commercial)

**Comment by takluyver** [comment]
Including the bird outline? Nice work! I'll certainly use it if there's a
free font that works for it.

**Comment by Carreau** [comment]
Roughly outline/drawn from pictures, Then Path Simplify. Distort, to feel
"lighter" Duplicated wing.

What do you think of
http://www.dafont.com/nemesia.font?text=FLIT+flit+Package+Manager&back=theme
?

**Comment by Carreau** [comment]
And I think that `flit <pkg> action` is a bit backward I would expect `flit install <pkg>`

**Comment by Carreau** [comment]
Also `flit <pkg> action --help` is confusing I found.

**Comment by rsyring** [comment]
Having a file for flit that is standard is the best IMO.  Just like tox.ini or setup.py, have a flit.ini.

>  I would have purely flit build, flit upload 

FWIW, I like this.

> I think I like the idea of having flit upload to build and upload it.

I wouldn't have a single command do both, that isn't very intuitive.  If you want to make a one-command option, continue to have a `--upload` option to `build` IMO.

**Comment by takluyver** [comment]
OK, thanks both - it's now flit.ini, and the package name is dropped from the command line. Otherwise, the command line options remain the same for now.
