### ISSUE TITLE
Where is the description string ?

### ISSUE THREAD

**Issue by lowks** [takluyver/flit#30]
I found some packages on `pypi` with empty `description` strings generated by flit. I see a `description-file`. Does that get translated to a `description` string ?

**Comment by takluyver** [comment]
The one-line description is taken from the first line of the docstring. The description-file is the equivalent of long_description in a setup.py script.

It looks like it gets it wrong if you write your module-level docstrings like this:


```python
"""
A really awesome package.

...
"""
```

I only tested with docstrings written like this:

```python
"""A really awesome package.

...
"""
```

Thanks for bringing it to my attention, I'll fix that.
