### ISSUE TITLE
check README is valid rst ?

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#31]
Of course PyPI does not do it, but if it can't compile the rst description, it throw the raw-text in it's place. 

(mistake in one of my package with code-block without a blank line)

I have few hope to have it fixed in PyPI, would be nice fro flit to maybe emit a warning...

**Comment by takluyver** [comment]
Good idea, I've been caught out by that before.

**Comment by Carreau** [comment]
Ok, so, docutils. I've mostly nothing.

The rst parser call a statemachine, the statemachine return a result that the parser ignore. The result does not contain trace of parsing error. The RSTstatemachine has an error function that does not appear to be called, even on debug mode. Some (Read all) errors are just directly printed to stderr so I went the other way: try a full conversion and try to find if I get errors. Though the html parser seem to just write the errors messages in the document itself.... Soooo fun.

**Comment by takluyver** [comment]
After some frustrating grepping of PyPI source code, gold!

https://pypi.python.org/pypi/readme
https://github.com/pypa/readme

No API docs, but it's pretty simple to work out from the source code.

**Comment by takluyver** [comment]
`distutils.command.check` also contains code to check the rst description. I'm not quite clear what differs between that and the readme module.

**Comment by Carreau** [comment]
Ha ! grepping through PyPI was what I would have done today ! Nice. I might
have a look later.

**Comment by Carreau** [comment]
Do we depends on distutils._check_rst_data ? is is an instance method that does not uses self, do you believe a patch to turn it into a staticmethod would be accepted ?

**Comment by takluyver** [comment]
Might be, though I know distutils doesn't get many changes now. If that code looks like what we want, I'd probably just copy the relevant bits out of distutils.

**Comment by takluyver** [comment]
This is done now.
