### ISSUE TITLE
Use backend-path again

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#316]
flit_core temporarily used intreehooks until pip supported the standard backend-path mechanism (#298). pip 20.0 does so, so we can return to the standard mechanism now.

**Comment by hroncok** [comment]
As a side note: If I read the spec right, backend-path needs to be list: https://www.python.org/dev/peps/pep-0517/#source-trees

**Comment by takluyver** [comment]
You're quite right. We got away with it because it's a single character and nothing in pip checks the type before iterating over it. Fixed in 7415c697874aaf0b277d078136e5a7f92eb01fe8.
