### ISSUE TITLE
Make docutils and requests non-mandatory

### ISSUE THREAD

**Issue by KOLANICH** [takluyver/flit#317]

**Comment by bpabel** [comment]
@takluyver Can this be closed? There's no explanation.

**Comment by KOLANICH** [comment]
>There's no explanation.

The title is the explaination itself.

**Comment by bpabel** [comment]
@KOLANICH Can you explain the reasoning for removing the dependencies?

**Comment by KOLANICH** [comment]
The features of `flit` using these dependencies are not needed on CI for me and I don't want CI to install unneeded packages. This is both an overhead and a security risk.

**Comment by bpabel** [comment]
If you really don’t want them installed, you can install flit with pip using the ‘—no-dependencies’ flag and handle installing the dependencies you want manually.

**Comment by KOLANICH** [comment]
It is not a correct approach.

**Comment by bpabel** [comment]
@KOLANICH out of curiosity, how are you using flit such that you don’t require those dependencies?

**Comment by KOLANICH** [comment]
Just install it and then install packages relying on flit to be built. I install packages from git repos of their authors, not from pypi, so I have to build them locally, but I don't need to upload anything to pypi (for my packages I use setuptools and my position is that my (and not only my) packages should be installed from their git, when it is feasible). ReadMe conversion is also not needed, I don't run CI pipelines to make them show ReadMe of packages, also I prefer MarkDown to ReSructuredText.

**Comment by bpabel** [comment]
@KOLANICH Ah, that might be the problem. Packages shouldn't require `flit` to be built.  `flit` is primarily a standalone build front-end and development tool.

The build backend should only require `flit_core`, which doesn't have either of the dependencies you listed.  If you're not using `flit` as a standalone tool and build front-end, there's no need to install `flit` or its dependencies.  If a package you are building has listed `flit` as a dependency, you may want to open a PR to have them change their dependency to `flit_core` instead.

**Comment by KOLANICH** [comment]
Thanks for the info. So I probably should remove `flit` from my base docker image, and for a frontend I can use `pep517`.

**Comment by bpabel** [comment]
Yeah, `pep517` should work.  The latest versions of `pip` can also build `pep517` packages.

**Comment by takluyver** [comment]
Yeah, I'd generally recommend using `pip` as a frontend. `pep517` has a kind of demo frontend, but it's been a recurring source of complaints (people assume it's meant to be a general purpose frontend and then file bugs when it doesn't do what they want), so we're planning to split it out to make the core API clearer.

**Comment by KOLANICH** [comment]
How can I insgall `flit_core` without installing `flit` using `pip` (and without using pypi or doing it manualy)? Should `flit_core` have an own `pyproject.toml`?

**Comment by takluyver** [comment]
> How can I insgall flit_core without installing flit using pip (and without using pypi or doing it manualy)?

I'm not exactly sure what your aim is. Normally, a frontend like pip will install `flit_core` automatically as part of the build process. If you want to install it separately, the obvious way is to get it from PyPI with `pip install flit_core`.

>  Should flit_core have an own pyproject.toml?

[It does!](https://github.com/takluyver/flit/blob/2.3.0/flit_core/pyproject.toml). So if you really need to install it from source, you can use pip on the directory containing that.
