### ISSUE TITLE
[BUG] flit --repository xyz publish != flit publish --repository xyz on MacOS

### ISSUE THREAD

**Issue by iwpnd** [takluyver/flit#321]
OS: macOS 10.15.3
flit: flit ==2.2.0

Docs state to use:
```bash
flit --repository testpypi publish
```
to specify custom server/credentials that are stored in `~/.pypirc`. However, on macOS this results in flit using the default PyPI server.

If you use:
```bash
flit publish --repository testpypi
```

results in the appropriate behavior.

**Comment by takluyver** [comment]
Oh, that's unfortunate. I moved the option, but I thought I could specify a hidden option in the old place so scripts would keep working:

https://github.com/takluyver/flit/blob/69ddf698a8d8d6e28a5f64ee9c7ab5d7651ffaae/flit/__init__.py#L52-L54

It sounds like they keep working but do the wrong thing. :-(

Do you want to make a PR removing that (so the old pattern errors rather than doing the wrong thing) and updating the docs?

**Comment by takluyver** [comment]
Or maybe the hidden option can be fixed by giving it a different [`dest` variable name](https://docs.python.org/3/library/argparse.html#dest).

**Comment by iwpnd** [comment]
Hi,
I never really worked with CLIs before, so I might not be the right person for the job. Yet, I would be happy to help and learn a thing or two.

Before I did anything I checked the behaviour of:

```python
# --repository now belongs on 'flit publish' - it's still here for 
# compatibility with scripts passing it before the subcommand. 
ap.add_argument('--repository', help=argparse.SUPPRESS)
```
It seems to always default to `None`, which is probably the behavior you intended.
If you use:
`flit --repository pypi publish --repository testpypi`

The latter will always overwrite the first.

So now if you were to apply your suggestions, you could:

```python
ap.add_argument(
    '--repository', 
    dest='deprecated_repository', 
    help=argparse.SUPPRESS
)
```
and then:
```python
    elif args.subcmd == 'publish':
        if args.deprecated_repository and args.repository:
            from .upload import main
            main(args.ini_file, args.repository, formats=set(args.format or []),
                gen_setup_py=args.setup_py)
        elif args.deprecated_repository:
            sys.exit("flit --repository is deprecated, use flit publish --repository instead.")
```

You could leave both options, with one resulting in a `sys.exit()` / error when provided,  and the other working correctly no matter if an argument is provided or not. Yet this still poses the question of why you keep the first argument if it has no use?

Is that something along the lines of what you had in mind?

**Comment by takluyver** [comment]
I was thinking of something similar, but with the logic like:

```python
if args.deprecated_repository:
    log.warning("Passing --repository before the 'upload' subcommand is deprecated: pass it after")
repository = args.repository or args.deprecated_repository
from .upload import main
main(args.ini_file, repository, ...)
```

So you get a warning plus expected behaviour, rather than an error. Now that it's already been broken for a while, this is maybe less important, but it's what I would have aimed for if I had noticed this before releasing it.

**Comment by iwpnd** [comment]
This would result in a warning, but also in a `KeyError` if I provided an argument that is not found in `.pypirc` - is this expected?

**Comment by takluyver** [comment]
That's already what happens if you use `flit publish --repository nonexistant` - so yup, expected behaviour. It might be good to have a nicer error message, but that's a separate issue.

**Comment by iwpnd** [comment]
I should’ve asked if it was okay for me to open a PR. Sorry about that.

**Comment by takluyver** [comment]
No problem, it is OK. I was hoping that you would. :-)
