### ISSUE TITLE
Using `flit-core` as a base for a custom wheel builder

### ISSUE THREAD

**Issue by mands** [takluyver/flit#339]
I'm looking to build wheels for a custom project and have seen it mentioned in a few places that `flit / flit-core` could be used as a basis for other custom PEP-517 backends.

One constraint I have is that the user's may have multiple wheels they want to build from the same directory, each with different requirements (we're working with data scientists whose code tends to be more experimental and wouldn't necessarily be familiar with `pyproject.toml`)

To support this, I'm thinking of generating temp `pyproject.toml` files as part of the build logic, which would then call `flit_core.wheel.make_wheel_in` with the path to the generated `pyproject.toml` - or perhaps create a wrapper around `WheelBuilder` that works directly with `LoadedConfig` objects so I can pass data structures from the builder directly.. 

Would such an approach make sense, or is there anything else you recommend? Similarly, are there any ideas around API stability for the rest of `flit_core` outside of `buildapi`?

Thanks!

**Comment by mands** [comment]
I figured out a way to handle this use-case by calling `flit.build.main` and doing some path manipulation to get the wheel built in the way required by our users.

Seems to work great - thanks for the library! :)

**Comment by dholth** [comment]
Tell me a little bit more. It sounds like you needed to generate the .dist-info metadata and the .zip (.whl) archive?

**Comment by takluyver** [comment]
Just to be clear, there's no promise of API stability for anything outside of `flit_core.buildapi` (the PEP 517 interface). Even `flit.build.main` isn't guaranteed; I'd recommend invoking it as a subprocess something like:

```python
subprocess.run([sys.executable, '-m', 'flit', 'build', ...])
```

Apart from the PEP 517 API, the public interface of flit is all [commands](https://flit.readthedocs.io/en/latest/cmdline.html), not Python functions.

**Comment by mands** [comment]
@dholth @takluyver - thanks for your replies, apologies for the delay in getting back - just to follow up with some more info, as I've now finished the project using flit to build wheels for a more of a custom deployment use-case.

Basically, we're need to package up data science scripts along with their dependencies and assets that can be deployed to a model deployment system we're building, and decided to use wheel's for the task. The issue is that most "in-the-wild" code isn't structured in a way that makes packaging as a wheel as easy as it could be - as it's more focussed on rapid development and experimentation.

For instance, given a directory layout like,
```
    ├── data
    │   └── approval_ratings.pickle
    ├── ticker.py
    ├── ticker_data.json
    ├── weekly_timeseries.ipynb
    └── plot_timeseries.py
```

User's may want to deploy/generate multiple wheels, using both `weekly_timeseries.ipynb` and `ticker.py` as the main modules, but all the code is developed in a single directory, with linked python dependencies (e.g. `plot_timeseries.py`) and binary assets.

We're using `flit` to build these wheels for deployment as it would allow end-users to specify which files to include/exclude along with handling addition python library requirements/dependencies, yet is much simpler for us to use and understand than tools like `setuptools` and so on.

In the end we have it now working, by basically code-generating a flit-compatible `pyproject.toml` and automagically creating some wrapper modules to capture the user's files as needed, and then calling flit to build the wheel. All is working great now, few issues like #343 which will hopefully be resolved by moving more things to `pyproject.toml` as optional metadata.

Thanks again for the great library! :) We'll hopefully be open-sourcing soon so can demonstrate a bit  further.
