### ISSUE TITLE
Unreconised key in flit.ini propose closes.

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#36]
like I mistype `requires` often.
Would be nice to have a did you mean.

**Comment by takluyver** [comment]
Seems reasonable, so long as it doesn't add much complexity. Do you know of a good package that can find the closest word to what you typed from a set of valid words?

**Comment by Carreau** [comment]
python [difflib: get_closest_match](https://docs.python.org/3/library/difflib.html#difflib.get_close_matches) It does not always works because the implementation is wrong. And I hates it. But it's simple enough.

**Comment by takluyver** [comment]
Good point, I'd forgotten about difflib. I imagine that for single words it can't go that badly wrong. Playing about with it a bit, I think it behaves better with the cutoff increased to 0.7 rather than the default of 0.6. Want to make a PR?

**Comment by Carreau** [comment]
Playing with [cffi](https://pypi.python.org/pypi/cffi_magic) for now.

**Comment by takluyver** [comment]
:-)

**Comment by takluyver** [comment]
Closed by #37
