### ISSUE TITLE
Add option to flit build to disable version normalisation

### ISSUE THREAD

**Issue by sethmlarson** [takluyver/flit#365]
I'd like to create dists with a version of `7.10-alpha0` to conform to my organizations version guidance.
Currently Flit normalizes versions to ones in PEP 440 but I'd like to disable this behavior.

Are you willing to accept a PR which adds a `--no-version-normalization` or equivalent?

**Comment by takluyver** [comment]
Sorry, not really. Flit is very much aimed at the 90% use case, and having some scheme to make sensible version numbers is good for the ecosystem as a whole.

**Comment by sethmlarson** [comment]
Yeah sorry for the noise, forgot to close this one after realizing normalization is required per the PEP. Thanks.

**Comment by takluyver** [comment]
No problem, thanks for being understanding about it.
