### ISSUE TITLE
flit install --pth-file breaks conda list

### ISSUE THREAD

**Issue by Koncopd** [takluyver/flit#367]
I tried to use `flit install --pth-file` on Windows and encountered the same problem as described [here](https://github.com/conda/conda/issues/9074).

**Comment by flying-sheep** [comment]
Pretty sure this is just conda having wrong expectations about what’s allowed to be in a `site-packages` directory. If I’m right, it’s the conda devs’ job to fix this, not flit’s to circumvent it (if at all possible)
