### ISSUE TITLE
In virtual environment populated with `flit install -s` (editable), `python3 -m pip freeze` raises `AssertionError` on MacOS

### ISSUE THREAD

**Issue by tombaker** [takluyver/flit#372]
When I populate a virtual environment with `flit install -s`, executing `python3 -m pip freeze` raises Pip's `AssertionError`.

I described this yesterday [on Stackoverflow](https://stackoverflow.com/questions/64339735/python-virtual-environments-created-since-mid-august-raise-assertionerror-for), then filed a [bug report for Pip](https://github.com/pypa/pip/issues/8996) with detailed instructions on how to reproduce the problem on MacOS 10.15.7 and Ubuntu 20.04.

Since then, however, I have noticed that `pip freeze` works in virtual environments populated using Flit 2.3.0 but not in environments populating using Flit 3.0.0. 

Is this possibly an issue for Flit (and not for Pip)?

**Comment by sbidoul** [comment]
@tombaker probably related to https://github.com/takluyver/flit/pull/335, but I think the fix should be done in pip.

**Comment by tombaker** [comment]
@sbidoul This has been [fixed in pip](https://github.com/pypa/pip/issues/8996), so I guess you could close this issue now - thanks!
