### ISSUE TITLE
Incorrect Docs --symlink

### ISSUE THREAD

**Issue by dougransom** [takluyver/flit#392]
--pth-file

> Create a .pth file in site-packages rather than copying the module, so you can test changes without reinstalling. This is a less elegant alternative to --symlink**, but it works on Windows, which typically doesn’t allow symlinks.**

Windows has supported Symlinks since Windows 7.  Most users have long since upgraded to Windows 7 or later.  It would be a rare install that has a file system on Windows that doesn't support symlinks.  Maybe change to 

> on file systems  that do no  allow symlinks

**Comment by takluyver** [comment]
From the Python docs for `os.symlink()`:

> On newer versions of Windows 10, unprivileged accounts can create symlinks if Developer Mode is enabled. When Developer Mode is not available/enabled, the SeCreateSymbolicLinkPrivilege privilege is required, or the process must be run as an administrator.

I think "typically doesn't allow symlinks" is a reasonable summary of that in a context where the details aren't super important. I carefully didn't say that Windows doesn't *support* symlinks, because I know it technically does. :wink:

**Comment by dougransom** [comment]
That is like saying "typically doesn't support pip" because in windows, you have to run pip in an elevated permission in order for the scripts to be placed in /Python/Scripts (ie. when you run pip install flit, you better be administrator or in a virtualenv).
