### ISSUE TITLE
Tagging / version inconsistency

### ISSUE THREAD

**Issue by henryiii** [takluyver/flit#397]
There does not seem to be a git tag for 3.1.0, though it's in the history file and on PyPI. And the docs claim the current version is 3.2.0 which does not seem to exist (but might just be a quirk of "latest" docs).

**Comment by takluyver** [comment]
Right, sorry, I must have forgotten to create the tag. Done now.

The 3.2.0 in the docs is indeed a quirk of 'latest' - I bumped the version number while testing something in PR #393. I'll hopefully get round to a new release soon.
