### ISSUE TITLE
PKG-INFO values mangled when using PEP 621 metadata

### ISSUE THREAD

**Issue by layday** [takluyver/flit#409]
In `PKG-INFO`, flit 3.2.0 has:

```
Home-page: None
Author: None
Author-email: Thomas Kluyver <thomas@kluyver.me.uk>
```

3.1.0 has:

```
Home-page: https://github.com/takluyver/flit
Author: Thomas Kluyver
Author-email: thomas@kluyver.me.uk
```

The 3.2.0 wheel `METADATA` do not have have a `Home-page` nor an `Author` and the `Author-email` is `Thomas Kluyver <thomas@kluyver.me.uk>`, like in the sdist.

When uploading an sdist with a `Home-Page` value of `None` using twine, the legacy upload API rejects it with:

```
'None' is an invalid value for Home-Page.
```

**Comment by takluyver** [comment]
Thanks. I think I previously thought that author & home-page were required fields, but in fact the only [required fields are metadata version, name and version](https://packaging.python.org/specifications/core-metadata/). It seems that PyPI accepts this, though (at least, I managed to upload Flit 3.2...).

In the longer term, I wonder if PKG-INFO will go away in favour of getting the metadata from the PEP 621 format directly.

**Comment by layday** [comment]
Easiest thing to do for the time being, I suppose would be to drop `Home-page` since PEP 621 omits it in favour of `Project-URL` and map it to `Project-URL: homepage, ...` when using the flit-specific metadata table.

**Comment by astrojuanlu** [comment]
So, the workaround is to remove the invalid keys from the sdist `PKG-INFO`? Does this have any unintended consequences?

**Comment by layday** [comment]
The workaround I've provided in #410 is to reuse the wheel metadata verbatim.  Removing the errant keys would also work - I imagine that if you were to only upload an sdist without `Home-page` to PyPI then it would not display a homepage URL and that'd be the only difference.  I don't know if anybody else makes use of `PKG-INFO` metadata and how they might be impacted by the loss of `Author` and `Home-page`, or by the switch to Core Metadata 2.1.
