### ISSUE TITLE
flit install should install dependencies

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#41]
The requires field should be a valid [requirements.txt](https://pip.pypa.io/en/latest/reference/pip_install.html#requirements-file-format) file, so we can shell out to pip to install these.

Suggestion from @minrk

**Comment by takluyver** [comment]
Annoyingly, as @jhamrick pointed out, requirements.txt is not the same format as the [requires-dist metadata](https://www.python.org/dev/peps/pep-0345/#requires-dist-multiple-use).

```
# requirements.txt
someproject>=3.0

# requires-dist
someproject (>=3.0)
```

So I guess I'll need to parse them to some extent.

**Comment by minrk** [comment]
Booooooo

**Comment by minrk** [comment]
@takluyver do you copy the requires field in flit.ini directly to to the wheel, or let it do the normal transforms that it does when coming from setup.py (i.e. converting from `pkg > 1` to `pkg (>1)`)? I would expect to specify `pkg > 1` in flit.ini.

**Comment by minrk** [comment]
#42 adds install, but doesn't handle the requires-dist != requirements issue yet, because it seems like the `requires` field in flit.ini should expect the requirements.txt format, not the Requires-Dist format.

**Comment by takluyver** [comment]
It does directly copy the requirements to the wheel metadata. One of my side goals here is to remove some of the unnecessary padding around Python packaging so that you're interacting with certain things more directly. I don't think the requirements.txt format is a clear improvement over the real metadata format, so I'd rather remove the intermediary and write in the metadata format directly.

**Comment by takluyver** [comment]
i.e. I think flit.ini should use the metadata format and translate to the pip format when needed, rather than vice versa. I'm open to arguments in favour of doing it the other way round, but that's my current preference.
