### ISSUE TITLE
Support alternativ location for .pypirc (for Azure Devops Pipelines)

### ISSUE THREAD

**Issue by decatur** [takluyver/flit#426]
Use case is to let `flit publish` on Azure Devops Pipelines.
All files created with a pipeline should reside in the Pipeline.Workspace, which typically points to something like `/home/vsts/work/1`.

As a helper Task, there is [TwineAuthenticateV1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/TwineAuthenticateV1), which creates a .pypirc in $PYPIRC_PATH. The latter defaulting to something like `/home/vsts/work/_temp/twineAuthenticate/zhVvTB/.pypirc`

Now ~ expands to `/home/vsts`, which is NOT documented to be writeable by pipelines.

So flit should support altering the location of the .pypirc file (like --config-file for twine)

Workaround: Move .pypirc to `/home/vsts`, which currently works.

[Typical pipeline definition with workaround](https://github.com/takluyver/flit/files/6907534/flit_issue.txt)

**Comment by takluyver** [comment]
The obvious way to pass credentials in a CI job is with environment variables, avoiding the need for a file entirely:

https://flit.readthedocs.io/en/latest/upload.html#using-environment-variables

**Comment by decatur** [comment]
No such luck.

Azure DevOps has a layered approach to security.
As a developer or distribution publisher, you do not own nor know the credentials to publish to an index.
These credentials are provided by the CI cloud administrator in the form of a service connection.
Which in turn will produce a .pypirc file.
See the [example](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#examples).

I figured it is easier to get `flit` patched than to move Azure DevOps 😉

**Comment by davidrft** [comment]
I think supporting an argument to specify the location of the pypirc file just as twine does would be the ideal.

**Comment by davidrft** [comment]
I would be happy to try and contribute if we agree on this. Thanks!

**Comment by decatur** [comment]
Suits me fine, i.e.

> --config-file CONFIG_FILE 
>     The .pypirc config file to use.

**Comment by takluyver** [comment]
OK, go for it. I might call the option something like `--pypirc` instead of `--config-file`, because 'config file' seems a bit generic, but other than that.

**Comment by davidrft** [comment]
I worked on the necessary changes to achieve this on #434. Could you please review it once you have some time? Thanks!
