### ISSUE TITLE
pyenvutils build with flit

### ISSUE THREAD

**Issue by dougransom** [takluyver/flit#430]
https://github.com/dougransom/pyenvutils build primarily with flit and a tiny amount of python, to provide information about the  python environment.  i think could be generally useful for those who live in a shell like bash, cmd, or powershell.  I am not sure how to get the word out.  I use it on some projects to push files to the site-packages folder, which could change depending on the python environment.

As an example, ````pye_executable````
would produce something like:
`c:\python38-32\python.exe`

It is in [pypi]( https://pypi.org/project/pyenvutils/)  but I am not sure how to get some more interest.

**Comment by takluyver** [comment]
Looks neat! Maybe you could try posting on the [Python discourse forum](https://discuss.python.org/c/users/7), or sites like the Python subreddit, or tweeting about it. :slightly_smiling_face:
