### ISSUE TITLE
Project dependencies aren't installed during editable install when metadata is specified via PEP 621  

### ISSUE THREAD

**Issue by ichard26** [takluyver/flit#432]
Hello!

I recently tried to move one of my projects' project metadata to PEP 621, but I hit a roadblock. Turns out that project dependencies aren't installed if flit is doing an editable install (doesn't matter if it's `--symlink` or `--pth`) with PEP 621. This doesn't occur with a normal `flit install` nor when using flit's custom metadata configuration.

**Reproduction**
- Clone https://github.com/ichard26/flit-pep621-editable-bug
- Setup a virtual environment
- cd into the `pep621` directory
- run `flit install --symlink` and observe how `click` isn't installed even it's specified in `pyproject.toml` under `[project.dependencies]`
```console
(venv) ichard26@acer-ubuntu:~/programming/oss/flit-pep621-editable-bug/pep621$ flit install --symlink
Extras to install for deps 'all': {'.none'}                                                                                             I-flit.install
Symlinking buggy.py -> /home/ichard26/programming/oss/flit-pep621-editable-bug/non-pep621/venv/lib/python3.8/site-packages/buggy.py     I-flit.install
```
- then compare that to `flit install` where `click` is in fact installed
```console
(venv) ichard26@acer-ubuntu:~/programming/oss/flit-pep621-editable-bug/pep621$ flit install
Extras to install for deps 'all': {'.none'}                                                                                             I-flit.install
Processing /home/ichard26/programming/oss/flit-pep621-editable-bug/pep621
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting click>=8.0.0
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Building wheels for collected packages: buggy
  Building wheel for buggy (PEP 517) ... done
  Created wheel for buggy: filename=buggy-21.8a1-py2.py3-none-any.whl size=1832 sha256=e9612d0bf6166c599c55f388df4a763dd76e160f978abcaaf71dc5a29f942145
  Stored in directory: /tmp/pip-ephem-wheel-cache-u9e1bwz8/wheels/fd/70/eb/8e679ea073d171fa3079117d8efb2bd5c6ae5c946e6cfd5982
Successfully built buggy
Installing collected packages: click, buggy
Successfully installed buggy-21.8a1 click-8.0.1

```
- but don't stop there, let's reset the env via `pip uninstall buggy click -y`
- cd back to the repo root and into the `non-pep621` directory
- run `flit install --symlink` and watch as `click` does get installed
```console
(venv) ichard26@acer-ubuntu:~/programming/oss/flit-pep621-editable-bug/non-pep621$ flit install --symlink
Extras to install for deps 'all': {'.none'}                                                                                             I-flit.install
Installing requirements                                                                                                                 I-flit.install
Collecting click>=8.0.0
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Installing collected packages: click
Successfully installed click-8.0.1
Symlinking bugfree.py -> /home/ichard26/programming/oss/flit-pep621-editable-bug/non-pep621/venv/lib/python3.8/site-packages/bugfree.py I-flit.install
```

**Environment**

- Python: CPython 3.8.5
- OS: Ubuntu 20.04.02 LTS
- pip: 21.2.4
- flit: 3.3.0

---

Anyway, thank you for all your work into flit! It's been awesome at making this personal project feel more like one instead of some annoying open source project wannabe :wink: In all seriousness, it simplifies packaging so much and it's amazing! If you need anything more from me feel free to ask away.

**Comment by takluyver** [comment]
Thanks for the thorough report! :+1:  This makes it easy to make a first guess at what's going wrong: I think the code path in `flit_core.config` that reads the PEP 621 metadata is not filling the `LoadedConfig.reqs_by_extra` attribute. I'll look in more detail today or tomorrow.

**Comment by takluyver** [comment]
Turns out it would go wrong when there were dependencies but no *optional* dependencies (so as a workaround, specifying some optional dependencies - or even an empty sub-table - should work). #433 should fix this.
