### ISSUE TITLE
Consider using `~=` in the `build-system.requires` field

### ISSUE THREAD

**Issue by pradyunsg** [takluyver/flit#452]
Currently, flit generates:

```
requires = ["flit_core >=3.2,<4"]
```

This is basically equivalent to:

```
requires = ["flit_core ~= 3.2"]
```

(okay, this is `flit_core >= 3.2, 3.*`, but that's basically what you want IIUC)

The later is much easier to read IMO, once you know what it means.

**Comment by takluyver** [comment]
I'd consider it, but I kind of like the explicit `<4`. At some point, I'll decide what breaking changes are going into v4 (e.g. it might drop the `[tool.flit.metadata]` table), and then the recommendation will be something like `>=3.2,<5` for projects following PEP 621. We already had this with the 'old style' TOML metadata, which worked with `>=2,<4`. I prefer just changing the numbers to swapping the operators.
