### ISSUE TITLE
Contradictory docs for --setup-py option in 3.5.0

### ISSUE THREAD

**Issue by mgorny** [takluyver/flit#469]
The docs in 3.5.0 are contradictory.

cmdline.rst says (https://github.com/takluyver/flit/commit/101a72c8f621a70f5308de109e539c4b621d66fc):

>    Generate a ``setup.py`` file in the sdist, so it can be installed by older
   versions of pip. This is the default for now, but a future version will
   disable this by default.

However, history.rst says (https://github.com/takluyver/flit/commit/b669e1f35e58af594b5d3eee6f1274cd6e78acb2):

> Flit no longer generates a ``setup.py`` file in sdists (``.tar.gz`` packages)
  by default

**Comment by takluyver** [comment]
Thanks - as you can probably guess, I forgot to update `cmdline.rst`.
