### ISSUE TITLE
Release on PyPI under a different name

### ISSUE THREAD

**Issue by c4ffein** [takluyver/flit#477]
As it is written in the documentation:
"Flit packages a single importable module or package at a time, using the import name as the name on PyPI. All subpackages and data files within a package are included automatically."
Could there be any way to specify a different release name for PyPI in the `pyproject.toml` than the module name?

**Comment by takluyver** [comment]
Yup, it is possible - using the same name is now just the default behaviour. Here's how you do it with new-style `[project]` metadata:

https://flit.readthedocs.io/en/latest/pyproject_toml.html#module-section

It's a bit different in the older style metadata, but also possible.

**Comment by c4ffein** [comment]
Thanks, I misread that section and never tried it with the `[project]` `name` as the one to release on PyPI
