### ISSUE TITLE
Investigate reproductible wheels.

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#58]
As far as I can tell it **should** be possible to reproduce byte for byte a wheel, is we sort the os.walkdir files and pass the right options to zipfile.

**Comment by takluyver** [comment]
Interesting. I looked into it for tar.gz files at one point and it seemed awkward, but perhaps it's easier with zip files.

**Comment by Carreau** [comment]
of interest : https://reproducible-builds.org/

**Comment by takluyver** [comment]
Thanks, reading up.

**Comment by Carreau** [comment]
Wheel package have the same issue:

https://bitbucket.org/pypa/wheel/pull-requests/52/apply-the-debian-patch-for-reproducible/diff

**Comment by takluyver** [comment]
#64 introduced reproducible builds :-)
