### ISSUE TITLE
flit.toml config files?

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#71]
I quite like [toml](https://github.com/toml-lang/toml), and I'm considering switching flit to use it for config files. It's a bit more verbose than ini, because string values have to be quoted, but there's a detailed specification, and it's quite a bit more flexible. We'd gain the ability to have lists (rather than just multiline strings), dates and arbitrarily nested dictionaries, rather than the strict two-level hierarchy we have with ini.

If I did this, I would still support ini files for backwards compatibility for quite some time. It would look for `flit.toml` first, and fall back to `flit.ini` if that wasn't found. When supplying the filename explicitly, it would try to parse it as toml if the extension was `.toml`, and as ini otherwise.

**Comment by Carreau** [comment]
+1 for toml.

**Comment by rochacbruno** [comment]
+1

**Comment by takluyver** [comment]
The plan for this is that, once PEP 517 is accepted, the metadata for flit will be stored in `pyproject.toml`, so that it doesn't need two separate packaging info files.

**Comment by brettcannon** [comment]
Should this issue be closed now that PEP 517 is accepted?

**Comment by takluyver** [comment]
Yup, this is now decided, even if the implementation isn't merged yet. Thanks for the reminder.
