### ISSUE TITLE
Hashes calculated in wrong format

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#73]
The hashes in a wheel's RECORD file are supposed to be in urlsafe base64, with trailing `=` removed, while flit is writing them in hex. Thanks to @sophacles for pointing this out.

**Comment by sophacles** [comment]
It's odd to me that `pip install file.whl` does work correctly on this. Not sure what that's about - but perhaps this should be reported to the pip folks as well?

**Comment by takluyver** [comment]
I guess flit doesn't check it - maybe it only checks if the wheel is signed?

**Comment by takluyver** [comment]
flit 0.8.1 is out with the fix for this.
