### ISSUE TITLE
force install without bumping version

### ISSUE THREAD

**Issue by jwkvam** [takluyver/flit#78]
Can I force flit to reinstall a package without bumping it's version number? I just wanted to do this for development purposes.

Edit: After submitting this I realized I could do this by appending "-dev" to the version, making it non-canonical.

**Comment by takluyver** [comment]
It's using pip to do the installation internally, so you can probably do the equivalent of pip's `--ignore-installed` flag by setting an [environment variable](https://pip.pypa.io/en/stable/user_guide/#environment-variables) called `PIP_IGNORE_INSTALLED`.

**Comment by jwkvam** [comment]
Thanks for the quick reply. That's helpful to know. I find the "-dev" version easier to use so I think I'll stick with that since I would prefer it to not be global.
