### ISSUE TITLE
Produce source distributions

### ISSUE THREAD

**Issue by dstufft** [takluyver/flit#8]
Packages without a sdist are, in my opinion, a bad idea in general. They cannot be packaged by downstream redistributors like Debian, Ubuntu, Fedora, etc because all of those have a policy of only accepting source distributions and Wheels are a binary format. Currently using flit essentially means that that particular package cannot be packaged in a downstream package repository *and* all of the things that depend on that particular package can also not be packaged in those downstream repositories.

In that vein, flit should produce working sdists and enable uploading them to PyPI.

**Comment by takluyver** [comment]
I wondered how far I'd get before someone asked for this. ;-)

I think there's really two separate questions here:

Is it important to put source tarballs on PyPI? To my mind, it's not: I put packages on PyPI so they can be installed with pip, and to some extent so they're discoverable when people search PyPI. Neither requires sdists. I've spent some time working with Debian packaging, and I know that it's no harder for them to use a source tarball from (say) Github than from PyPI.

What should distros do about source tarballs that don't have a setup.py? I'd like them to be happy - declarative metadata should be much simpler to reuse for their purposes than an imperative setup script. However, if they prefer to turn it into a setup.py file, it should also be straightforward for them to write tools to do that. I don't consider that a core function of flit, however. But even if it was, the setup.py would be a generated file, not genuinely part of the source, so it wouldn't belong in a source tarball.

I'm happy to continue discussion on this, but for now I'm comfortable saying that the source tarball for flit 0.2 is at https://github.com/takluyver/flit/archive/0.2.tar.gz

**Comment by dstufft** [comment]
Well, it's not entirely true that you only need Wheels to install with pip.

For example:

* Immediately off the bat, you're throwing away every pip older than 1.5 (by default) or 1.4 (opt in) which, as of Sept of 2014, ~40% of all pip isntalls were using a version of pip older than 1.4.
* You also break the ``--no-use-wheel`` feature, which is something people will generally use when the Wheel for something they want to install is broken (or perhaps might just be compiled with options other than what they want).

However, PyPI is also more than just pip. While pip is now the recommended installer, easy_install/setuptools is still an important installer (~10% of the installation traffic in Sept of 2014 was setuptools). In fact pip itself will invoke setuptools to do an install of ``setup_requires``, which does not support Wheels.

If you decide not to support "real" sdists (as defined by defacto standardization by distutils/setuptools) then you should at least be upfront that using flit would prevent ~40% (10% setuptools + 30% pip < 1.4) of the installer traffic on PyPI (as measured from September of 2014) from being able to install a project.

**Comment by takluyver** [comment]
I should probably make it clearer that this is kind of an experiment in how we can do things if we focus on the nicer new bits of Python packaging and don't worry about the details of setuptools or old versions of pip. In a similar vein, flit only runs with Python 3, even though I'm quite sure it would attract more users if it ran on Python 2 as well.

**Comment by takluyver** [comment]
I've added a note about it to the README.
