### ISSUE TITLE
Try to upload on wharehouse by default ?

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#80]
https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

Thoughts ?

**Comment by takluyver** [comment]
Makes sense, assuming our upload code works with it. The URL would need to be changed [here](https://github.com/takluyver/flit/blob/530d2e465029c3c391bdc76e28b4e556e005d8b9/flit/upload.py#L18) and added [here](https://github.com/takluyver/flit/blob/530d2e465029c3c391bdc76e28b4e556e005d8b9/flit/upload.py#L60-L61). It would still be overridden if you have the standard PyPI URL in `~/.pypirc`, though with a little more code we could turn the old URL into the new one.

Is there also a warehouse-based testpypi we can stick some releases on to test?

See also #51, which is about improving the UX when pypirc doesn't exist or doesn't contain the expected data.

**Comment by takluyver** [comment]
Just tested this by changing my pypirc file - it [works](https://pypi.io/project/jupyter_kernel_test/), but the logging tells you:

```
Package is at https://upload.pypi.io/legacy//jupyter_kernel_test
```

It's assuming that the repository will follow the same URL format as PyPI classic.

**Comment by Carreau** [comment]
Yes the warehouse website is actually backed by the same datastore as usual PyPI.

**Comment by takluyver** [comment]
Yep, but the code can't assume a fixed URL, either - you might be uploading to another PyPI instance (like testpypi, or a private index).

**Comment by Carreau** [comment]
True, true. 

That's might be something we can ask to Donald: Is there something in the API to return the URL where one can see the uploaded package.

**Comment by takluyver** [comment]
As the URL we're using now is `https://upload.pypi.io/legacy/`, I guess there is or will be a new upload API, which might give information like that. @dstufft, is that guess right?

**Comment by dstufft** [comment]
I plan on adding a new, better, upload API at some point yes.

**Comment by takluyver** [comment]
To record from distutils-sig: the PSF has bought the pypi.org domain, so the preferred URL is now https://upload.pypi.org/legacy/

**Comment by takluyver** [comment]
The `upload.pypi.org` URL is now the default for uploads. I've opened #110 for the misleading log message.
